"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState, type FormEvent } from "react";
import type { JobView } from "@/contracts/job";
import type { WorldView } from "@/contracts/world";

type SafeWorld = Omit<WorldView, "adminPassword" | "serverPassword" | "env">;
async function json<T>(input: RequestInfo, init?: RequestInit): Promise<T> {
  const response = await fetch(input, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
  const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body;
}
function Status({ value }: { value: SafeWorld["status"] }) { return <span className={`status status-${value}`}><i />{value}</span>; }

export function Dashboard() {
  const queryClient = useQueryClient(); const [dialogOpen, setDialogOpen] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const worldsQuery = useQuery({ queryKey: ["worlds"], queryFn: async () => (await json<{ worlds: SafeWorld[] }>("/api/worlds")).worlds });
  const jobsQuery = useQuery({ queryKey: ["jobs"], queryFn: async () => (await json<{ jobs: JobView[] }>("/api/jobs?limit=12")).jobs });
  const worlds = useMemo(() => worldsQuery.data ?? [], [worldsQuery.data]);
  const action = useMutation({ mutationFn: ({ id, name }: { id: string; name: string }) => json<{ jobId: string }>(`/api/worlds/${id}/actions`, { method: "POST", body: JSON.stringify({ action: name }) }), onSuccess: () => { setNotice("Operation queued"); void queryClient.invalidateQueries({ queryKey: ["jobs"] }); }, onError: (error) => setNotice(error.message) });
  const create = useMutation({ mutationFn: (payload: Record<string, unknown>) => json("/api/worlds", { method: "POST", body: JSON.stringify(payload) }), onSuccess: () => { setDialogOpen(false); setNotice("World registered"); void queryClient.invalidateQueries({ queryKey: ["worlds"] }); }, onError: (error) => setNotice(error.message) });
  const counts = useMemo(() => ({ running: worlds.filter((world) => world.status === "running").length, operations: (jobsQuery.data ?? []).filter((job) => job.state === "running" || job.state === "queued").length }), [worlds, jobsQuery.data]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); create.mutate({ displayName: values.get("displayName"), installDir: values.get("installDir"), platform: values.get("platform"), gamePort: Number(values.get("gamePort")), queryPort: Number(values.get("queryPort")), restApiPort: Number(values.get("restApiPort")), rconPort: Number(values.get("rconPort")) }); }
  const run = (world: SafeWorld, name: string) => action.mutate({ id: world.id, name });

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span><div><strong>Palworld</strong><small>Server Manager</small></div></div><nav><a className="active" href="#worlds">Overview</a><a href="#operations">Operations</a><a href="#settings">Settings</a></nav><div className="sidebar-foot"><span className="pulse" />Local manager online<small>Core-first alpha</small></div></aside><main className="workspace">
    <header className="topbar"><div><p className="eyebrow">CONTROL PLANE</p><h1>Server fleet</h1></div><Dialog.Root open={dialogOpen} onOpenChange={setDialogOpen}><Dialog.Trigger asChild><button className="button primary">+ Add server</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog"><Dialog.Title>Add a Palworld server</Dialog.Title><Dialog.Description>Register an existing directory or choose an empty directory for a new install.</Dialog.Description><form onSubmit={submit} className="form-grid"><label>Name<input required name="displayName" placeholder="Family server" /></label><label className="wide">Install directory<input required name="installDir" placeholder="/data/palworld/family" /></label><label>Platform<select name="platform"><option value="linux">Linux</option><option value="windows">Windows / Wine</option></select></label><label>Game port<input name="gamePort" type="number" defaultValue={8211 + worlds.length * 10} /></label><label>Query port<input name="queryPort" type="number" defaultValue={27015 + worlds.length} /></label><label>REST API port<input name="restApiPort" type="number" defaultValue={8212 + worlds.length * 10} /></label><label>RCON port<input name="rconPort" type="number" defaultValue={25575 + worlds.length} /></label><div className="dialog-actions"><Dialog.Close asChild><button type="button" className="button ghost">Cancel</button></Dialog.Close><button className="button primary" disabled={create.isPending}>Register server</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root></header>
    {notice && <button className="notice" onClick={() => setNotice(null)}>{notice}<span>×</span></button>}
    <section className="summary-grid"><article><span>Registered</span><strong>{worlds.length}</strong><small>independent worlds</small></article><article><span>Running</span><strong className="green">{counts.running}</strong><small>healthy processes</small></article><article><span>Operations</span><strong className="amber">{counts.operations}</strong><small>queued or active</small></article></section>
    <section id="worlds"><div className="section-title"><div><p className="eyebrow">WORLDS</p><h2>Managed servers</h2></div><button className="icon-button" onClick={() => worldsQuery.refetch()} aria-label="Refresh">↻</button></div>{worldsQuery.isLoading ? <div className="empty">Loading registry…</div> : worldsQuery.error ? <div className="empty error">{worldsQuery.error.message}</div> : worlds.length === 0 ? <div className="empty"><div><strong>No servers registered</strong><p>Add an existing Palworld install or provision a new one.</p></div></div> : <div className="world-grid">{worlds.map((world) => <article className="world-card" key={world.id}><div className="world-head"><div className="world-icon">{world.displayName.slice(0, 1).toUpperCase()}</div><div><h3>{world.displayName}</h3><Status value={world.status} /></div><span className="platform">{world.platform}</span></div><dl><div><dt>Game</dt><dd>{world.gamePort}</dd></div><div><dt>Query</dt><dd>{world.queryPort}</dd></div><div><dt>REST</dt><dd>{world.restApiPort}</dd></div><div><dt>Build</dt><dd>{world.buildId ?? "—"}</dd></div></dl><p className="path" title={world.installDir}>{world.installDir}</p><div className="world-actions">{world.status === "running" ? <><button onClick={() => run(world, "restart")}>Restart</button><button className="danger" onClick={() => run(world, "stop")}>Stop</button></> : <><button className="start" onClick={() => run(world, "start")}>Start</button><button onClick={() => run(world, world.buildId ? "update" : "install")}>{world.buildId ? "Update" : "Install"}</button></>}<button onClick={() => run(world, "backup")}>Backup</button></div></article>)}</div>}</section>
    <section id="operations" className="operations"><div className="section-title"><div><p className="eyebrow">ACTIVITY</p><h2>Recent operations</h2></div></div><div className="job-list">{(jobsQuery.data ?? []).length === 0 ? <p className="muted padded">No operations yet.</p> : (jobsQuery.data ?? []).map((job) => <div className="job" key={job.id}><span className={`job-state ${job.state}`} /><div><strong>{job.kind}</strong><small>{job.message}{job.error ? ` — ${job.error}` : ""}</small></div><div className="progress"><i style={{ width: `${job.progress}%` }} /></div><time>{new Date(job.createdAt).toLocaleString()}</time></div>)}</div></section>
  </main></div>;
}
