"use client";
import * as Dialog from "@radix-ui/react-dialog";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState, type FormEvent } from "react";
import type { JobView } from "@/contracts/job";
import type { WorldView } from "@/contracts/world";
import { JobLogDialog } from "./job-log-dialog";
import { AppShell } from "./app-shell";

type SafeWorld = Omit<WorldView, "adminPassword" | "serverPassword" | "env">;
async function json<T>(input: RequestInfo, init?: RequestInit): Promise<T> {
  const response = await fetch(input, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
  const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body;
}
function Status({ value }: { value: SafeWorld["status"] }) { return <span className={`status status-${value}`}><i />{value}</span>; }

export function Dashboard() {
  const queryClient = useQueryClient(); const [dialogOpen, setDialogOpen] = useState(false); const [createMode, setCreateMode] = useState<"install" | "adopt">("install"); const [installDir, setInstallDir] = useState(""); const [selectedJob, setSelectedJob] = useState<JobView | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const worldsQuery = useQuery({ queryKey: ["worlds"], queryFn: async () => (await json<{ worlds: SafeWorld[] }>("/api/worlds")).worlds });
  const jobsQuery = useQuery({ queryKey: ["jobs"], queryFn: async () => (await json<{ jobs: JobView[] }>("/api/jobs?limit=12")).jobs });
  const worlds = useMemo(() => worldsQuery.data ?? [], [worldsQuery.data]);
  const action = useMutation({ mutationFn: ({ id, name }: { id: string; name: string }) => json<{ jobId: string }>(`/api/worlds/${id}/actions`, { method: "POST", body: JSON.stringify({ action: name }) }), onSuccess: () => { setNotice("Operation queued"); void queryClient.invalidateQueries({ queryKey: ["jobs"] }); }, onError: (error) => setNotice(error.message) });
  const create = useMutation({ mutationFn: ({ payload, mode }: { payload: Record<string, unknown>; mode: "install" | "adopt" }) => json<{ world: SafeWorld }>(`/api/worlds${mode === "adopt" ? "?mode=adopt" : ""}`, { method: "POST", body: JSON.stringify(payload) }), onSuccess: async ({ world }, { mode }) => { setDialogOpen(false); setInstallDir(""); setNotice(mode === "install" ? "Server installation queued" : "Existing server registered"); void queryClient.invalidateQueries({ queryKey: ["worlds"] }); if (mode === "install") { try { await json(`/api/worlds/${world.id}/actions`, { method: "POST", body: JSON.stringify({ action: "install" }) }); } catch (error) { setNotice(`World registered, but installation could not be queued: ${error instanceof Error ? error.message : String(error)}`); } } void queryClient.invalidateQueries({ queryKey: ["jobs"] }); }, onError: (error) => setNotice(error.message) });
  const counts = useMemo(() => ({ running: worlds.filter((world) => world.status === "running").length, operations: (jobsQuery.data ?? []).filter((job) => job.state === "running" || job.state === "queued").length }), [worlds, jobsQuery.data]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); create.mutate({ mode: createMode, payload: { displayName: values.get("displayName"), installDir, platform: values.get("platform"), gamePort: Number(values.get("gamePort")), queryPort: Number(values.get("queryPort")), restApiPort: Number(values.get("restApiPort")), rconPort: Number(values.get("rconPort")) } }); }
  async function chooseDirectory() { const selected = await window.psmDesktop?.pickDirectory(); if (selected) setInstallDir(selected); }
  const run = (world: SafeWorld, name: string) => action.mutate({ id: world.id, name });

  return <AppShell active="worlds">
    <header className="topbar"><div><p className="eyebrow">WORLDS</p><h1>Palworld servers</h1></div><Dialog.Root open={dialogOpen} onOpenChange={setDialogOpen}><Dialog.Trigger asChild><button className="button primary">+ New world</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog create-dialog"><Dialog.Title>Add a world</Dialog.Title><Dialog.Description>Install a fresh dedicated server or register one already on disk.</Dialog.Description><div className="create-mode"><button className={createMode === "install" ? "active" : ""} onClick={() => setCreateMode("install")}><strong>Install new server</strong><span>Download a separate Palworld server with SteamCMD.</span></button><button className={createMode === "adopt" ? "active" : ""} onClick={() => setCreateMode("adopt")}><strong>Use existing server</strong><span>Register a folder containing PalServer without downloading it again.</span></button></div><form onSubmit={submit} className="form-grid"><label>Name<input required name="displayName" placeholder={createMode === "install" ? "New Palworld world" : "Existing world"} /></label><label>Platform<select name="platform"><option value="linux">Linux</option><option value="windows">Windows / Wine</option></select></label><label className="wide">{createMode === "install" ? "Empty installation directory" : "Existing PalServer directory"}<span className="path-picker"><input required value={installDir} onChange={(event) => setInstallDir(event.target.value)} placeholder="/data/palworld/family" /><button type="button" onClick={() => void chooseDirectory()}>Browse…</button></span></label><label>Game port<input name="gamePort" type="number" defaultValue={8211 + worlds.length * 10} /></label><label>Query port<input name="queryPort" type="number" defaultValue={27015 + worlds.length} /></label><label>REST API port<input name="restApiPort" type="number" defaultValue={8212 + worlds.length * 10} /></label><label>RCON port<input name="rconPort" type="number" defaultValue={25575 + worlds.length} /></label><div className="dialog-actions"><Dialog.Close asChild><button type="button" className="button ghost">Cancel</button></Dialog.Close><button className="button primary" disabled={create.isPending}>{create.isPending ? "Working…" : createMode === "install" ? "Install server" : "Add this server"}</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root></header>
    {notice && <button className="notice" onClick={() => setNotice(null)}>{notice}<span>×</span></button>}
    <section className="summary-grid"><article><span>Registered</span><strong>{worlds.length}</strong><small>independent worlds</small></article><article><span>Running</span><strong className="green">{counts.running}</strong><small>healthy processes</small></article><article><span>Operations</span><strong className="amber">{counts.operations}</strong><small>queued or active</small></article></section>
    <section id="worlds">
      <div className="section-title"><div><p className="eyebrow">WORLDS</p><h2>Managed servers</h2></div><button className="icon-button" onClick={() => worldsQuery.refetch()} aria-label="Refresh">↻</button></div>
      {worldsQuery.isLoading ? <div className="empty">Loading registry…</div> : worldsQuery.error ? <div className="empty error">{worldsQuery.error.message}</div> : worlds.length === 0 ? <div className="empty"><div><strong>No servers registered</strong><p>Add an existing Palworld install or provision a new one.</p></div></div> : <div className="world-grid">{worlds.map((world) => <article className="world-card" key={world.id}>
        <div className="world-head"><div className="world-icon">{world.displayName.slice(0, 1).toUpperCase()}</div><div><h3>{world.displayName}</h3><Status value={world.status} /></div><span className="platform">{world.platform}</span></div>
        <dl><div><dt>Game</dt><dd>{world.gamePort}</dd></div><div><dt>Query</dt><dd>{world.queryPort}</dd></div><div><dt>REST</dt><dd>{world.restApiPort}</dd></div><div><dt>Build</dt><dd>{world.buildId ?? "—"}</dd></div></dl>
        <p className="path" title={world.installDir}>{world.installDir}</p><div className="world-actions fleet-actions">{world.status === "running" ? <><button onClick={() => run(world, "restart")}>Restart</button><button className="danger" onClick={() => run(world, "stop")}>Stop</button></> : <button className="start" onClick={() => run(world, "start")}>Start</button>}<Link className="manage-link" href={`/worlds/${world.id}`}>Manage</Link></div>
      </article>)}</div>}
    </section>
    <section id="operations" className="operations"><div className="section-title"><div><p className="eyebrow">ACTIVITY</p><h2>Recent operations</h2></div></div><div className="job-list">{(jobsQuery.data ?? []).length === 0 ? <p className="muted padded">No operations yet.</p> : (jobsQuery.data ?? []).map((job) => <button className="job job-button" key={job.id} onClick={() => setSelectedJob(job)}><span className={`job-state ${job.state}`} /><span><strong>{job.kind}</strong><small>{job.message}{job.error ? ` — ${job.error}` : ""}</small></span><span className="progress"><i style={{ width: `${job.progress}%` }} /></span><time>{new Date(job.createdAt).toLocaleString()}</time></button>)}</div></section>
    {selectedJob && <JobLogDialog job={selectedJob} onClose={() => setSelectedJob(null)} />}
  </AppShell>;
}
