"use client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState, type FormEvent } from "react";

type Code = { id: string; codeHint: string; label: string; scope: "all" | "world"; worldId: string | null; permissions: string[]; enabled: boolean; createdAt: number; lastUsedAt: number | null };
type Session = { id: string; codeId: string; lastSeenAt: number; expiresAt: number; revokedAt: number | null; ipAddress: string | null; userAgent: string | null };
type Audit = { id: number; principalLabel: string; action: string; worldId: string | null; detail: string | null; ipAddress: string | null; createdAt: number };
type Access = { settings: { enabled: boolean }; codes: Code[]; sessions: Session[]; audit: Audit[] };
type World = { id: string; displayName: string };
type Network = { configuredHost: "127.0.0.1" | "0.0.0.0"; activeHost: "127.0.0.1" | "0.0.0.0"; port: number; addresses: string[] };
const permissionOptions = [{ id: "world.view", label: "View world status" }, { id: "world.lifecycle", label: "Start, stop, and restart" }, { id: "world.players", label: "View and moderate players" }, { id: "world.messages", label: "Send server messages" }];
async function request<T>(body?: unknown): Promise<T> { const response = await fetch("/api/remote/access", body === undefined ? undefined : { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || `Request failed (${response.status})`); return result; }

export function RemoteAccessSettings({ onNotice }: { onNotice(message: string): void }) {
  const client = useQueryClient(); const access = useQuery({ queryKey: ["remote-access"], queryFn: () => request<Access>() });
  const worlds = useQuery({ queryKey: ["worlds", "remote-settings"], queryFn: async () => { const response = await fetch("/api/worlds"); const body = await response.json(); if (!response.ok) throw new Error(body.error); return body.worlds as World[]; } });
  const [network, setNetwork] = useState<Network | null>(null); const [host, setHost] = useState<"127.0.0.1" | "0.0.0.0">("127.0.0.1"); const [label, setLabel] = useState(""); const [scope, setScope] = useState<"all" | "world">("all"); const [worldId, setWorldId] = useState(""); const [permissions, setPermissions] = useState(["world.view", "world.lifecycle"]); const [revealedCode, setRevealedCode] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { const desktop = window.psmDesktop; if (!desktop) return; void desktop.getManagerNetwork().then((value) => { setNetwork(value); setHost(value.configuredHost); }); }, []);
  const enabled = access.data?.settings.enabled ?? false;
  async function saveAccess(nextEnabled = enabled) {
    const desktop = window.psmDesktop; if (!desktop) return onNotice("LAN binding is available only in the desktop application."); setSaving(true);
    try {
      if (!nextEnabled) await desktop.setManagerHost("127.0.0.1");
      await request({ action: "set-enabled", enabled: nextEnabled });
      const result = await desktop.setManagerHost(nextEnabled ? host : "127.0.0.1");
      await client.invalidateQueries({ queryKey: ["remote-access"] }); setNetwork((current) => current ? { ...current, configuredHost: result.configuredHost } : current);
      onNotice(result.restartRequired ? `${nextEnabled ? "Remote access settings saved" : "Remote access disabled"}. Restart the manager to apply the network binding.` : nextEnabled ? "Remote access is enabled." : "Remote access is disabled and all sessions were revoked.");
    } catch (error) { onNotice(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); }
  }
  async function createCode(event: FormEvent) { event.preventDefault(); setSaving(true); try { const result = await request<{ code: Code & { code: string } }>({ action: "create-code", value: { label, scope, worldId: scope === "world" ? worldId : null, permissions } }); setRevealedCode(result.code.code); setLabel(""); await client.invalidateQueries({ queryKey: ["remote-access"] }); onNotice("Access code created. Copy it now; it cannot be shown again."); } catch (error) { onNotice(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); } }
  async function codeAction(body: unknown, message: string) { try { await request(body); await client.invalidateQueries({ queryKey: ["remote-access"] }); onNotice(message); } catch (error) { onNotice(error instanceof Error ? error.message : String(error)); } }
  const restartRequired = network && network.configuredHost !== network.activeHost;
  return <section className="settings-remote"><div className="settings-section-heading"><div><h2>Authenticated remote administration</h2><p>Allow scoped access from another device. Existing manager pages remain desktop-only; remote users receive a restricted control screen.</p></div><button className={`toggle ${enabled ? "on" : ""}`} disabled={saving || access.isLoading} onClick={() => void saveAccess(!enabled)}><i />{enabled ? "On" : "Off"}</button></div>
    <div className="remote-network-grid"><label>Network binding<select disabled={!network} value={host} onChange={(event) => setHost(event.target.value as typeof host)}><option value="127.0.0.1">This computer only (127.0.0.1)</option><option value="0.0.0.0">Local network (all interfaces)</option></select></label><div><strong>Remote address</strong><small>{host === "0.0.0.0" && network?.addresses.length ? network.addresses.map((address) => `http://${address}:${network.port}/remote`).join(" · ") : `http://127.0.0.1:${network?.port ?? 4318}/remote`}</small></div><button className="button" disabled={!enabled || saving || !network} onClick={() => void saveAccess(true)}>Save binding</button></div>
    {restartRequired && <p className="remote-warning">Restart required: the manager is currently listening on {network.activeHost === "0.0.0.0" ? "the LAN" : "this computer only"}.</p>}
    <div className="remote-management-grid"><form className="remote-code-form" onSubmit={createCode}><h3>Create access code</h3><label>Person or device<input value={label} maxLength={80} onChange={(event) => setLabel(event.target.value)} placeholder="e.g. Samuel's phone" /></label><label>World access<select value={scope} onChange={(event) => setScope(event.target.value as typeof scope)}><option value="all">All worlds</option><option value="world">One world</option></select></label>{scope === "world" && <label>World<select required value={worldId} onChange={(event) => setWorldId(event.target.value)}><option value="">Select a world</option>{worlds.data?.map((world) => <option value={world.id} key={world.id}>{world.displayName}</option>)}</select></label>}<fieldset><legend>Permissions</legend>{permissionOptions.map((permission) => <label key={permission.id}><input type="checkbox" checked={permissions.includes(permission.id)} onChange={(event) => setPermissions((current) => event.target.checked ? [...current, permission.id] : current.filter((id) => id !== permission.id))} />{permission.label}</label>)}</fieldset><button className="button primary" disabled={!enabled || saving || !label.trim() || !permissions.length}>Create code</button>{revealedCode && <div className="revealed-code"><small>Copy this code now</small><strong>{revealedCode}</strong><button type="button" onClick={() => void navigator.clipboard.writeText(revealedCode)}>Copy</button></div>}</form>
      <div className="remote-code-list"><h3>Access codes</h3>{access.data?.codes.map((code) => { const active = access.data.sessions.filter((session) => session.codeId === code.id && !session.revokedAt && session.expiresAt > Date.now()).length; return <article key={code.id}><div><strong>{code.label}</strong><small>••••{code.codeHint} · {code.scope === "all" ? "all worlds" : worlds.data?.find((world) => world.id === code.worldId)?.displayName ?? "one world"} · {active} active session{active === 1 ? "" : "s"}</small></div><div><button onClick={() => void codeAction({ action: "update-code", id: code.id, value: { enabled: !code.enabled } }, code.enabled ? "Access code disabled and its sessions revoked." : "Access code enabled.")}>{code.enabled ? "Disable" : "Enable"}</button><button onClick={() => void codeAction({ action: "revoke-sessions", codeId: code.id }, "Remote sessions revoked.")}>Sign out</button><button className="danger" onClick={() => window.confirm(`Delete access for ${code.label}?`) && void codeAction({ action: "delete-code", id: code.id }, "Access code deleted.")}>Delete</button></div></article>; })}{!access.data?.codes.length && <p className="muted">No remote access codes have been created.</p>}</div></div>
    <details className="remote-audit"><summary>Remote activity ({access.data?.audit.length ?? 0} recent records)</summary><div className="record-list">{access.data?.audit.map((entry) => <div key={entry.id}><span><strong>{entry.principalLabel} · {entry.action}</strong><small>{entry.detail ?? entry.worldId ?? "Remote access event"} · {new Date(entry.createdAt).toLocaleString()} · {entry.ipAddress ?? "unknown address"}</small></span></div>)}</div></details>
  </section>;
}
