"use client";
import { useQuery } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { useTranslation } from "react-i18next";

type Player = { name?: string; playername?: string; userId?: string; userid?: string; playerId?: string; level?: number };
type World = { id: string; displayName: string; status: "stopped" | "starting" | "running" | "stopping" | "crashed" | "unknown"; gamePort: number; buildId: string | null; players?: Player[] };
type Session = { label: string; permissions: string[] };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }

export function RemoteAccessPage() {
  const { t } = useTranslation();
  const remote = useQuery({ queryKey: ["remote-worlds"], queryFn: async () => {
    const result = await request<{ session: Session; worlds: World[] }>("/api/remote/worlds");
    if (!result.session.permissions.includes("world.players")) return result;
    const worlds = await Promise.all(result.worlds.map(async (world) => {
      if (world.status !== "running") return world;
      try { const status = await request<{ players: { players?: Player[] } | Player[] | null }>(`/api/remote/worlds/${world.id}/players`); return { ...world, players: Array.isArray(status.players) ? status.players : status.players?.players ?? [] }; }
      catch { return world; }
    }));
    return { ...result, worlds };
  }, retry: false, refetchInterval: 5_000 });
  const session = remote.data?.session ?? null; const worlds = remote.data?.worlds ?? []; const [code, setCode] = useState(""); const [message, setMessage] = useState(""); const [unbanId, setUnbanId] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  async function login(event: FormEvent) { event.preventDefault(); setError(null); try { await request("/api/remote/login", { method: "POST", body: JSON.stringify({ code }) }); setCode(""); await remote.refetch(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  async function action(world: World, name: string) { setBusy(world.id); setError(null); try { await request(`/api/remote/worlds/${world.id}/actions`, { method: "POST", body: JSON.stringify({ action: name }) }); await remote.refetch(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(null); } }
  async function logout() { await request("/api/remote/logout", { method: "POST" }); await remote.refetch(); }
  async function admin(world: World, payload: Record<string, unknown>) { setBusy(world.id); setError(null); try { await request(`/api/remote/worlds/${world.id}/admin`, { method: "POST", body: JSON.stringify(payload) }); setMessage(""); setUnbanId(""); await remote.refetch(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(null); } }
  if (!session) return <main className="remote-login"><form onSubmit={login}><span className="brand-mark">P</span><p className="eyebrow">{t("remote.login.eyebrow")}</p><h1>{t("remote.login.title")}</h1><p>{t("remote.login.description")}</p><label>{t("remote.login.code")}<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} autoFocus /></label>{error && <p className="error-text">{error}</p>}<button className="button primary" disabled={code.length !== 6}>{t("remote.login.signIn")}</button></form></main>;
  const lifecycle = session.permissions.includes("world.lifecycle");
  return <main className="remote-manager"><header><div><p className="eyebrow">{t("remote.eyebrow")}</p><h1>{t("remote.title")}</h1><p>{t("remote.signedIn", { name: session.label })}</p></div><button className="button ghost" onClick={() => void logout()}>{t("remote.signOut")}</button></header>{error && <p className="remote-error">{error}</p>}<div className="remote-worlds">{worlds.map((world) => <article key={world.id}><div className="remote-world-summary"><span className={`status status-${world.status}`}><i />{t(`status.${world.status}`)}</span><h2>{world.displayName}</h2><p>{t("remote.summary", { port: world.gamePort, build: world.buildId ?? t("common.unknown").toLocaleLowerCase() })}</p>{session.permissions.includes("world.players") && world.status === "running" && <div className="remote-players"><strong>{t("remote.online", { count: world.players?.length ?? 0 })}</strong>{world.players?.map((player, index) => { const userId = String(player.userId ?? player.userid ?? player.playerId ?? index); const name = String(player.name ?? player.playername ?? t("common.unknownPlayer")); return <span key={userId}>{name} <small>{t("remote.level", { level: player.level ?? "—" })}</small><button disabled={busy === world.id} onClick={() => void admin(world, { action: "kick", userId, playerName: name })}>{t("players.kick")}</button><button className="danger" disabled={busy === world.id} onClick={() => window.confirm(t("players.banConfirm", { name })) && void admin(world, { action: "ban", userId, playerName: name })}>{t("players.ban")}</button></span>; })}<form className="remote-message" onSubmit={(event) => { event.preventDefault(); void admin(world, { action: "unban", userId: unbanId }); }}><input value={unbanId} maxLength={128} onChange={(event) => setUnbanId(event.target.value)} placeholder={t("remote.bannedPlayer")} /><button disabled={!unbanId.trim() || busy === world.id}>{t("players.unban")}</button></form></div>}{session.permissions.includes("world.messages") && world.status === "running" && <form className="remote-message" onSubmit={(event) => { event.preventDefault(); void admin(world, { action: "announce", message }); }}><input value={message} maxLength={2000} onChange={(event) => setMessage(event.target.value)} placeholder={t("remote.announcement")} /><button disabled={!message.trim() || busy === world.id}>{t("remote.send")}</button></form>}</div>{lifecycle && <div className="remote-actions">{world.status === "stopped" || world.status === "crashed" ? <button className="button primary" disabled={busy === world.id} onClick={() => void action(world, "start")}>{t("common.start")}</button> : <><button className="button" disabled={busy === world.id} onClick={() => void action(world, "restart")}>{t("common.restart")}</button><button className="button danger" disabled={busy === world.id} onClick={() => void action(world, "stop")}>{t("common.stop")}</button></>}</div>}</article>)}</div></main>;
}
