"use client";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { AppShell } from "./app-shell";
import { Toast } from "./toast";

type Paths = { dataDirectory: string; database: string; steamCmd: string; logs: string };
export function SettingsPage() {
  const query = useQuery({ queryKey: ["app-settings"], queryFn: async () => { const response = await fetch("/api/settings"); const body = await response.json(); if (!response.ok) throw new Error(body.error); return body.settings as Paths; } });
  const [closeToTray, setCloseToTray] = useState(true); const [launchAtLogin, setLaunchAtLogin] = useState(false); const [desktopReady, setDesktopReady] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { const desktop = window.psmDesktop; if (!desktop) return; void Promise.all([desktop.getCloseToTray(), desktop.getLaunchAtLogin()]).then(([close, launch]) => { setCloseToTray(close); setLaunchAtLogin(launch); setDesktopReady(true); }); }, []);
  async function toggleClose() { const desktop = window.psmDesktop; if (!desktop) return; const value = await desktop.setCloseToTray(!closeToTray); setCloseToTray(value); setNotice(value ? "Closing the window will keep the manager in the tray." : "Closing the window will exit the manager."); }
  async function toggleLaunch() { const desktop = window.psmDesktop; if (!desktop) return; try { const value = await desktop.setLaunchAtLogin(!launchAtLogin); setLaunchAtLogin(value); setNotice(value ? "The manager will start hidden at login." : "Launch at login disabled."); } catch (error) { setNotice(error instanceof Error ? error.message : String(error)); } }
  return <AppShell active="settings"><header className="topbar"><div><p className="eyebrow">APPLICATION</p><h1>Settings</h1><p className="page-subtitle">Desktop behavior and manager-owned storage.</p></div></header><Toast message={notice} onDismiss={() => setNotice(null)} /><div className="settings-sections"><section><div><h2>Close to system tray</h2><p>Keep the manager and supervised servers operating when the window is closed. Quit fully from the tray menu.</p></div><button className={`toggle ${closeToTray ? "on" : ""}`} disabled={!desktopReady} onClick={() => void toggleClose()}><i />{closeToTray ? "On" : "Off"}</button></section><section><div><h2>Launch at login</h2><p>Start the manager hidden in the tray after signing in so worlds with autostart enabled can recover without opening the window.</p></div><button className={`toggle ${launchAtLogin ? "on" : ""}`} disabled={!desktopReady} onClick={() => void toggleLaunch()}><i />{launchAtLogin ? "On" : "Off"}</button></section><section className="settings-paths"><div><h2>Manager data</h2><p>The rewrite keeps its database, SteamCMD, logs, and backups separate from the legacy manager.</p></div>{query.data && <dl><div><dt>Data directory</dt><dd>{query.data.dataDirectory}</dd></div><div><dt>Database</dt><dd>{query.data.database}</dd></div><div><dt>SteamCMD</dt><dd>{query.data.steamCmd}</dd></div><div><dt>Logs</dt><dd>{query.data.logs}</dd></div></dl>}<button className="button ghost" disabled={!desktopReady || !query.data} onClick={() => void window.psmDesktop?.openPath(query.data!.dataDirectory)}>Open data folder</button></section></div></AppShell>;
}
