"use client";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type ReactNode } from "react";
import { useTranslation } from "react-i18next";
import type { WorldView } from "@/contracts/world";
import { WorldPropertiesPanel, WorldServerSetupPanel } from "./world-edit-dialog";
import { WorldSchedulesPanel } from "./world-schedules-dialog";
import { WorldBackupsPanel } from "./world-backups-panel";
import { AppShell } from "./app-shell";
import { StructuredSettings } from "./structured-settings";
import { Toast } from "./toast";
import { humanizeIdentifier } from "@/lib/job-presentation";
import { useJobPresentation } from "@/lib/use-job-presentation";
import { useLocaleDateTime } from "@/lib/use-locale-format";
import { BuildStatus } from "./build-status";

type SafeWorld = Omit<WorldView, "adminPassword" | "serverPassword" | "env">;
type Tab = "overview" | "players" | "deaths" | "console" | "settings" | "backups" | "schedule" | "admin";
type Live = { reachable: boolean; info?: Record<string, unknown>; players?: { players?: Array<Record<string, unknown>> }; metrics?: Record<string, unknown>; error?: string };
type Activity = { events: Array<{ id: number; kind: string; message: string; createdAt: number }>; sessions: Array<{ id: number; playerName: string | null; event: string; createdAt: number }>; deaths: Array<{ id: number; victim: string; cause: string | null; killer: string | null; killerKind: string | null; createdAt: number }>; hasMore: { events: boolean; sessions: boolean; deaths: boolean } };
type Logs = { files: string[]; selected: string | null; sizeBytes?: number; content: string };
type Configuration = { path: string; exists: boolean; content: string; running: boolean };
type ConfigVersion = { id: string; note: string | null; createdAt: number; sizeBytes: number };

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }
const tabs: Tab[] = ["overview", "players", "deaths", "console", "settings", "backups", "schedule", "admin"];
export function WorldWorkspace({ worldId }: { worldId: string }) {
  const { t } = useTranslation(); const presentation = useJobPresentation(); const stamp = useLocaleDateTime();
  const client = useQueryClient(); const [tab, setTab] = useState<Tab>("overview"); const [settingsMode, setSettingsMode] = useState<"guided" | "raw">("guided"); const [notice, setNotice] = useState<string | null>(null); const [draft, setDraft] = useState<string | null>(null); const [logsPaused, setLogsPaused] = useState(false); const [selectedLog, setSelectedLog] = useState<string>(); const [activityLimit, setActivityLimit] = useState(25);
  const worldQuery = useQuery({ queryKey: ["world", worldId], queryFn: async () => (await json<{ world: SafeWorld }>(`/api/worlds/${worldId}`)).world, refetchInterval: 4_000 });
  const world = worldQuery.data;
  const liveQuery = useQuery({ queryKey: ["world-status", worldId], queryFn: async () => (await json<{ status: Live }>(`/api/worlds/${worldId}/status`)).status, refetchInterval: world?.status === "running" ? 5_000 : false });
  const activityQuery = useQuery({ queryKey: ["world-activity", worldId, activityLimit], queryFn: async () => (await json<{ activity: Activity }>(`/api/worlds/${worldId}/activity?limit=${activityLimit}`)).activity, refetchInterval: 10_000 });
  const logsQuery = useQuery({ queryKey: ["world-logs", worldId, selectedLog], queryFn: async () => (await json<{ logs: Logs }>(`/api/worlds/${worldId}/logs${selectedLog ? `?file=${encodeURIComponent(selectedLog)}` : ""}`)).logs, refetchInterval: tab === "console" && world?.status === "running" && !logsPaused ? 2_000 : false });
  const configurationQuery = useQuery({ queryKey: ["configuration", worldId], queryFn: async () => (await json<{ configuration: Configuration }>(`/api/worlds/${worldId}/configuration`)).configuration });
  const versionsQuery = useQuery({ queryKey: ["configuration-versions", worldId], queryFn: async () => (await json<{ versions: ConfigVersion[] }>(`/api/worlds/${worldId}/configuration/versions`)).versions });
  const action = useMutation({ mutationFn: (payload: Record<string, unknown>) => json<{ jobId: string }>(`/api/worlds/${worldId}/actions`, { method: "POST", body: JSON.stringify(payload) }), onSuccess: (_, payload) => { setNotice(`${presentation.startingMessage(String(payload.action))}…`); void client.invalidateQueries({ queryKey: ["world", worldId] }); void client.invalidateQueries({ queryKey: ["jobs"] }); }, onError: (error) => setNotice(error.message) });
  const saveConfig = useMutation({ mutationFn: () => json(`/api/worlds/${worldId}/configuration`, { method: "PUT", body: JSON.stringify({ content: draft ?? configurationQuery.data?.content ?? "" }) }), onSuccess: () => { setNotice(t("world.config.saved")); void configurationQuery.refetch(); void versionsQuery.refetch(); void client.invalidateQueries({ queryKey: ["configuration-options", worldId] }); }, onError: (error) => setNotice(error.message) });
  const restoreConfig = useMutation({ mutationFn: (versionId: string) => json<{ result: { content: string } }>(`/api/worlds/${worldId}/configuration/versions/${versionId}/restore`, { method: "POST" }), onSuccess: ({ result }) => { setDraft(result.content); setNotice(t("world.config.restored")); void versionsQuery.refetch(); void client.invalidateQueries({ queryKey: ["configuration", worldId] }); void client.invalidateQueries({ queryKey: ["configuration-options", worldId] }); }, onError: (error) => setNotice(error.message) });
  if (worldQuery.isLoading) return <AppShell active="worlds" className="world-workspace"><div className="empty">{t("world.loading")}</div></AppShell>;
  if (!world) return <AppShell active="worlds" className="world-workspace"><div className="empty error">{t("world.notFound")}</div></AppShell>;
  const live = liveQuery.data; const metrics = live?.metrics ?? {}; const players = live?.players?.players ?? [];
  const run = (name: string) => action.mutate({ action: name });
  return <AppShell active="worlds" className="world-workspace">
    <Link className="back-link" href="/">{t("world.allWorlds")}</Link>
    <Toast message={notice} onDismiss={() => setNotice(null)} />
    <section className="world-banner"><div className="world-banner-head"><div className="world-icon large">{world.displayName.slice(0, 1).toUpperCase()}</div><div className="world-title"><div><h1>{world.displayName}</h1><Status value={world.status} /></div><p>{String(live?.info?.servername ?? world.installDir)}</p></div><div className="world-primary-actions">{world.status === "running" ? <><button className="button ghost" onClick={() => run("restart")}>{t("common.restart")}</button><button className="button danger" onClick={() => run("stop")}>{t("common.stop")}</button></> : world.status === "starting" || world.status === "stopping" ? <button className="button" disabled>{t(world.status === "starting" ? "world.starting" : "world.stopping")}</button> : <button className="button primary" onClick={() => run("start")}>{t("common.start")}</button>}<button className="button ghost" disabled={world.status === "starting" || world.status === "stopping"} onClick={() => run("check-update")}>{t("world.checkBuild")}</button><button className="button ghost" disabled={world.status === "running" || world.status === "starting" || world.status === "stopping"} onClick={() => run(world.buildId ? "update" : "install")}>{t(world.latestBuildId && world.buildId !== world.latestBuildId ? "world.updateAvailable" : "world.update")}</button></div></div>
      <div className="quick-stats"><Quick label={t("world.stat.players")} value={live?.reachable ? `${players.length}/${String(metrics.maxplayernum ?? "—")}` : "—"} /><Quick label={t("world.stat.uptime")} value={formatUptime(Number(metrics.uptime ?? 0), live?.reachable, t)} /><Quick label={t("world.stat.day")} value={live?.reachable ? String(metrics.days ?? "—") : "—"} /><Quick label={t("world.stat.fps")} value={live?.reachable ? String(metrics.serverfps ?? "—") : "—"} /><Quick label={t("world.stat.build")} value={<BuildStatus installed={world.buildId} latest={world.latestBuildId} />} /><Quick label={t("world.stat.port")} value={String(world.gamePort)} /></div>
      <div className="connection-row"><span>{t("world.connect")}</span><code>127.0.0.1:{world.gamePort}</code><button onClick={() => void navigator.clipboard.writeText(`127.0.0.1:${world.gamePort}`)}>{t("common.copy")}</button></div>
    </section>
    <div className="world-tabs">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{t(`world.tab.${item}`)}</button>)}</div>
    <section className="world-tab-panel">
      {tab === "overview" && <Overview activity={activityQuery.data} live={live} onLoadOlder={() => setActivityLimit((value) => Math.min(500, value + 25))} />}
      {tab === "players" && <Players worldId={worldId} players={players} reachable={Boolean(live?.reachable)} onRefresh={() => void liveQuery.refetch()} onNotice={setNotice} />}
      {tab === "deaths" && <Deaths records={activityQuery.data?.deaths ?? []} hasMore={Boolean(activityQuery.data?.hasMore.deaths)} onLoadOlder={() => setActivityLimit((value) => Math.min(500, value + 25))} />}
      {tab === "console" && <Console world={world} logs={logsQuery.data} paused={logsPaused} onPause={() => setLogsPaused((value) => !value)} onSelect={setSelectedLog} onRefresh={() => void logsQuery.refetch()} onNotice={setNotice} />}
      {tab === "settings" && <div><div className="settings-mode"><button className={settingsMode === "guided" ? "active" : ""} onClick={() => setSettingsMode("guided")}>{t("world.config.guided")}</button><button className={settingsMode === "raw" ? "active" : ""} onClick={() => setSettingsMode("raw")}>{t("world.config.raw")}</button></div>{settingsMode === "guided" ? <div className="guided-configuration"><WorldServerSetupPanel world={world} onSaved={() => void worldQuery.refetch()} onNotice={setNotice} /><StructuredSettings worldId={worldId} onNotice={setNotice} /></div> : <><div className="panel-heading"><div><h2>PalWorldSettings.ini</h2><p>{configurationQuery.data?.path}</p></div><button className="button primary" disabled={saveConfig.isPending} onClick={() => saveConfig.mutate()}>{t("world.config.saveRaw")}</button></div><textarea className="settings-editor" value={draft ?? configurationQuery.data?.content ?? ""} onChange={(event) => setDraft(event.target.value)} spellCheck={false} /><h2 className="settings-history-title">{t("world.config.history")}</h2><div className="record-list">{(versionsQuery.data ?? []).map((version) => <div key={version.id}><span><strong>{version.note ?? t("world.config.version")}</strong><small>{stamp(version.createdAt)} · {t("world.config.bytes", { count: version.sizeBytes })}</small></span><button disabled={restoreConfig.isPending || world.status === "running"} onClick={() => restoreConfig.mutate(version.id)}>{t("world.config.restore")}</button></div>)}{!(versionsQuery.data ?? []).length && <p className="muted">{t("world.config.noVersions")}</p>}</div></>}</div>}
      {tab === "backups" && <WorldBackupsPanel worldId={worldId} running={world.status === "running"} onBackup={() => action.mutate({ action: "backup", reason: "manual" })} onRestore={(backupId) => { if (window.confirm(t("world.backupRestoreConfirm"))) action.mutate({ action: "restore", backupId }); }} onNotice={setNotice} />}
      {tab === "schedule" && <WorldSchedulesPanel world={world} onNotice={setNotice} />}
      {tab === "admin" && <WorldPropertiesPanel world={world} onSaved={() => void worldQuery.refetch()} onNotice={setNotice} />}
    </section>
  </AppShell>;
}
function Status({ value }: { value: SafeWorld["status"] }) { const { t } = useTranslation(); return <span className={`status status-${value}`}><i />{t(`status.${value}`)}</span>; }
function Quick({ label, value }: { label: string; value: ReactNode }) { return <article><strong>{value}</strong><span>{label}</span></article>; }
function formatUptime(seconds: number, reachable: boolean | undefined, t: (key: string, options?: Record<string, unknown>) => string) { if (!reachable) return "—"; const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return t("world.uptimeFormat", { hours, minutes }); }
function Overview({ activity, live, onLoadOlder }: { activity?: Activity; live?: Live; onLoadOlder(): void }) { const { t } = useTranslation(); const stamp = useLocaleDateTime(); const hasMore = Boolean(activity?.hasMore.events || activity?.hasMore.sessions); return <div className="overview-columns"><section><h2>{t("overview.activity")}</h2>{(activity?.events ?? []).length ? activity!.events.map((item) => <div className="history-row" key={item.id}><strong>{t(`events.kind.${item.kind}`, { defaultValue: humanizeIdentifier(item.kind) })}</strong><span>{item.message}</span><time>{stamp(item.createdAt)}</time></div>) : <p className="muted">{t("overview.noEvents")}</p>}</section><section><h2>{t("overview.sessions")}</h2>{(activity?.sessions ?? []).length ? activity!.sessions.map((item) => <div className="history-row" key={item.id}><strong>{t(`events.kind.${item.event}`, { defaultValue: humanizeIdentifier(item.event) })}</strong><span>{item.playerName ?? t("common.unknownPlayer")}</span><time>{stamp(item.createdAt)}</time></div>) : <p className="muted">{t("overview.noSessions")}</p>}<h2 className="health-heading">{t("overview.health")}</h2><p className={live?.reachable ? "green" : "muted"}>{live?.reachable ? t("overview.reachable") : live?.error ?? t("overview.offline")}</p>{hasMore && <button className="button ghost history-more" onClick={onLoadOlder}>{t("overview.loadOlder")}</button>}</section></div>; }
function Players({ worldId, players, reachable, onRefresh, onNotice }: { worldId: string; players: Array<Record<string, unknown>>; reachable: boolean; onRefresh(): void; onNotice(message: string): void }) {
  const { t } = useTranslation();
  const [manualUserId, setManualUserId] = useState("");
  const admin = useMutation({
    mutationFn: (payload: Record<string, unknown>) => json(`/api/worlds/${worldId}/admin`, { method: "POST", body: JSON.stringify(payload) }),
    onSuccess: (_, payload) => { const action = String(payload.action); const name = String(payload.playerName ?? payload.userId ?? "player"); onNotice(t(action === "kick" ? "players.kicked" : action === "ban" ? "players.banned" : "players.unbanned", { name })); onRefresh(); },
    onError: (error) => onNotice(error.message),
  });
  function act(action: "kick" | "ban" | "unban", userId: string, name: string) {
    if (action !== "unban" && !window.confirm(t(action === "kick" ? "players.kickConfirm" : "players.banConfirm", { name }))) return;
    admin.mutate({ action, userId, playerName: name });
  }
  if (!reachable) return <div className="tab-empty"><h2>{t("players.title")}</h2><p>{t("players.offlineHelp")}</p></div>;
  return <div className="players-panel"><div className="panel-heading"><div><h2>{t("players.online")}</h2><p>{t("players.idHelp")}</p></div><button className="button ghost" onClick={onRefresh}>{t("common.refresh")}</button></div>
    {players.length ? <div className="player-table"><div className="player-table-head"><span>{t("players.player")}</span><span>{t("players.level")}</span><span>{t("players.ping")}</span><span>{t("players.location")}</span><span>{t("players.actions")}</span></div>{players.map((player, index) => { const userId = String(player.userId ?? player.userid ?? player.playerId ?? player.name ?? index); const name = String(player.name ?? player.playername ?? t("common.unknownPlayer")); return <div className="player-row" key={userId}><span><strong>{name}</strong><small>{String(player.accountName ?? player.accountname ?? userId)}</small></span><span>{String(player.level ?? "—")}</span><span>{player.ping == null ? "—" : `${Math.round(Number(player.ping))} ms`}</span><span>{player.location_x == null ? "—" : `${Math.round(Number(player.location_x))}, ${Math.round(Number(player.location_y))}`}</span><span className="player-actions"><button disabled={admin.isPending} onClick={() => act("kick", userId, name)}>{t("players.kick")}</button><button className="danger" disabled={admin.isPending} onClick={() => act("ban", userId, name)}>{t("players.ban")}</button></span></div>; })}</div> : <div className="tab-empty compact"><p>{t("players.none")}</p></div>}
    <section className="manual-moderation"><div><h2>{t("players.moderate")}</h2><p>{t("players.moderateHelp")}</p></div><input value={manualUserId} onChange={(event) => setManualUserId(event.target.value)} placeholder={t("players.userId")} /><button disabled={!manualUserId.trim() || admin.isPending} onClick={() => act("kick", manualUserId.trim(), manualUserId.trim())}>{t("players.kick")}</button><button className="danger" disabled={!manualUserId.trim() || admin.isPending} onClick={() => act("ban", manualUserId.trim(), manualUserId.trim())}>{t("players.ban")}</button><button disabled={!manualUserId.trim() || admin.isPending} onClick={() => act("unban", manualUserId.trim(), manualUserId.trim())}>{t("players.unban")}</button></section>
  </div>;
}

function Deaths({ records, hasMore, onLoadOlder }: { records: Activity["deaths"]; hasMore: boolean; onLoadOlder(): void }) {
  const { t } = useTranslation(); const stamp = useLocaleDateTime();
  return <div><div className="panel-heading"><div><h2>{t("deaths.title")}</h2><p>{t("deaths.description")}</p></div></div>{records.length ? <div className="record-list">{records.map((item) => <div key={item.id}><span><strong>{item.victim}</strong><small>{item.killer ? `${item.cause ?? t("deaths.unknownCause")} · ${t(item.killerKind === "player" ? "deaths.killedByPlayer" : "deaths.killedBy")} ${item.killer}` : item.cause ?? t("deaths.unknownCause")}</small><small>{stamp(item.createdAt)}</small></span></div>)}</div> : <div className="tab-empty"><h2>{t("deaths.empty")}</h2><p>{t("deaths.emptyHelp")}</p></div>}{hasMore && <button className="button ghost history-more" onClick={onLoadOlder}>{t("overview.loadOlder")}</button>}</div>;
}

function Console({ world, logs, paused, onPause, onSelect, onRefresh, onNotice }: { world: SafeWorld; logs?: Logs; paused: boolean; onPause(): void; onSelect(file: string): void; onRefresh(): void; onNotice(message: string): void }) {
  const { t } = useTranslation();
  const [search, setSearch] = useState(""); const [announcement, setAnnouncement] = useState(""); const [rconCommand, setRconCommand] = useState(""); const [rconOutput, setRconOutput] = useState("");
  const admin = useMutation({ mutationFn: (payload: Record<string, unknown>) => json(`/api/worlds/${world.id}/admin`, { method: "POST", body: JSON.stringify(payload) }), onSuccess: (_, payload) => { if (payload.action === "announce") { setAnnouncement(""); onNotice(t("console.announcementSent")); } else onNotice(t("console.saveRequested")); }, onError: (error) => onNotice(error.message) });
  const rcon = useMutation({ mutationFn: (command: string) => json<{ output: string }>(`/api/worlds/${world.id}/rcon`, { method: "POST", body: JSON.stringify({ command }) }), onSuccess: ({ output }, command) => { setRconOutput(`> ${command}\n${output || t("console.noResponse")}`); setRconCommand(""); }, onError: (error) => { setRconOutput(t("console.error", { error: error.message })); onNotice(error.message); } });
  const needle = search.trim().toLocaleLowerCase(); const lines = (logs?.content ?? "").split("\n"); const matches = needle ? lines.filter((line) => line.toLocaleLowerCase().includes(needle)) : lines; const shown = matches.join("\n");
  return <div className="console-panel"><div className="panel-heading"><div><h2>{t("console.title")}</h2><p>{logs?.selected ?? t("console.noLog")}{logs?.sizeBytes && logs.sizeBytes > 250_000 ? ` · ${t("console.newest")}` : ""}</p></div><div className="console-heading-actions"><button className={`button ${paused ? "primary" : "ghost"}`} onClick={onPause}>{t(paused ? "console.resume" : "console.pause")}</button><button className="button ghost" onClick={onRefresh}>{t("console.refresh")}</button></div></div>
    <div className="console-tools"><label>{t("console.logFile")}<select value={logs?.selected ?? ""} onChange={(event) => onSelect(event.target.value)} disabled={!logs?.files.length}>{(logs?.files ?? []).map((file) => <option key={file}>{file}</option>)}</select></label><label>{t("console.search")}<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t("console.searchPlaceholder")} /></label>{logs?.selected && <a className="button ghost" href={`/api/worlds/${world.id}/logs/download?file=${encodeURIComponent(logs.selected)}`}>{t("console.download")}</a>}<span>{needle ? t("console.matches", { count: matches.length }) : t(paused ? "console.paused" : "console.updating")}</span></div>
    <pre className="console-output">{shown || t(needle ? "console.noMatches" : "console.waiting")}</pre>
    <section className="live-admin"><div><h2>{t("console.adminTitle")}</h2><p>{t("console.adminDescription")}</p></div><div className="announce-row"><input value={announcement} maxLength={2_000} onChange={(event) => setAnnouncement(event.target.value)} placeholder={t("console.announcement")} disabled={world.status !== "running" || !world.restApiEnabled} /><button className="button primary" disabled={!announcement.trim() || admin.isPending || world.status !== "running" || !world.restApiEnabled} onClick={() => admin.mutate({ action: "announce", message: announcement })}>{t("console.send")}</button><button className="button ghost" disabled={admin.isPending || world.status !== "running" || !world.restApiEnabled} onClick={() => admin.mutate({ action: "save" })}>{t("console.saveWorld")}</button></div>{!world.restApiEnabled && <p className="form-warning">{t("console.restDisabled")}</p>}</section>
    {world.rconEnabled && <section className="legacy-rcon"><div><h2>{t("console.rconTitle")}</h2><p>{t("console.rconDescription")}</p></div><div className="announce-row"><input value={rconCommand} onChange={(event) => setRconCommand(event.target.value)} placeholder={t("console.rconPlaceholder")} disabled={world.status !== "running"} onKeyDown={(event) => { if (event.key === "Enter" && rconCommand.trim() && !rcon.isPending) rcon.mutate(rconCommand); }} /><button className="button ghost" disabled={!rconCommand.trim() || rcon.isPending || world.status !== "running"} onClick={() => rcon.mutate(rconCommand)}>{t(rcon.isPending ? "console.running" : "console.run")}</button></div>{rconOutput && <pre className="rcon-output">{rconOutput}</pre>}</section>}
  </div>;
}
