"use client";
import * as Dialog from "@radix-ui/react-dialog";
import * as Tabs from "@radix-ui/react-tabs";
import { useQuery } from "@tanstack/react-query";
import type { WorldView } from "@/contracts/world";

type SafeWorld = Omit<WorldView, "adminPassword" | "serverPassword" | "env">;
type Activity = { events: Array<{ id: number; kind: string; message: string; createdAt: number }>; sessions: Array<{ id: number; playerName: string | null; event: string; createdAt: number }>; deaths: Array<{ id: number; victim: string; cause: string | null; killer: string | null; createdAt: number }> };
type Logs = { files: string[]; selected: string | null; sizeBytes?: number; content: string };
type LiveStatus = { reachable: boolean; info: unknown; players: unknown; metrics: unknown; error?: string };
async function get<T>(url: string): Promise<T> { const response = await fetch(url); const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }

export function WorldMonitorDialog({ world, onClose }: { world: SafeWorld; onClose(): void }) {
  const logs = useQuery({ queryKey: ["world-logs", world.id], queryFn: async () => (await get<{ logs: Logs }>(`/api/worlds/${world.id}/logs`)).logs, refetchInterval: world.status === "running" ? 2_000 : 10_000 });
  const activity = useQuery({ queryKey: ["world-activity", world.id], queryFn: async () => (await get<{ activity: Activity }>(`/api/worlds/${world.id}/activity`)).activity, refetchInterval: 10_000 });
  const status = useQuery({ queryKey: ["world-live-status", world.id], queryFn: async () => (await get<{ status: LiveStatus }>(`/api/worlds/${world.id}/status`)).status, refetchInterval: world.status === "running" ? 5_000 : false });
  const playerPayload = status.data?.players as { players?: unknown[] } | null | undefined;
  return <Dialog.Root open onOpenChange={(open) => { if (!open) onClose(); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog monitor-dialog"><Dialog.Title>{world.displayName} operations</Dialog.Title><Dialog.Description>Live server health, console output, and persistent operational history.</Dialog.Description><Tabs.Root defaultValue="console"><Tabs.List className="tab-list"><Tabs.Trigger value="console">Console</Tabs.Trigger><Tabs.Trigger value="health">Health & players</Tabs.Trigger><Tabs.Trigger value="events">History</Tabs.Trigger></Tabs.List>
    <Tabs.Content value="console"><div className="monitor-toolbar"><span>{logs.data?.selected ?? "No server log yet"}</span><span>{logs.data?.sizeBytes ? `${Math.ceil(logs.data.sizeBytes / 1024)} KiB` : ""}</span><button onClick={() => void logs.refetch()}>Refresh</button></div><pre className="console-output">{logs.isLoading ? "Loading log…" : logs.data?.content || "No log output has been recorded for this world."}</pre></Tabs.Content>
    <Tabs.Content value="health"><div className="health-summary"><article><span>Process</span><strong>{world.status}</strong></article><article><span>REST API</span><strong className={status.data?.reachable ? "green" : ""}>{status.data?.reachable ? "reachable" : "offline"}</strong></article><article><span>Players</span><strong>{playerPayload?.players?.length ?? "—"}</strong></article></div>{status.data?.error && <p className="error-text">{status.data.error}</p>}<div className="json-grid"><section><h4>Server info</h4><pre>{JSON.stringify(status.data?.info, null, 2) || "Not available"}</pre></section><section><h4>Metrics</h4><pre>{JSON.stringify(status.data?.metrics, null, 2) || "Not available"}</pre></section><section><h4>Players</h4><pre>{JSON.stringify(status.data?.players, null, 2) || "Not available"}</pre></section></div></Tabs.Content>
    <Tabs.Content value="events"><div className="history-grid"><section><h4>Events</h4>{(activity.data?.events ?? []).map((item) => <div className="history-row" key={item.id}><strong>{item.kind}</strong><span>{item.message}</span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</section><section><h4>Sessions</h4>{(activity.data?.sessions ?? []).map((item) => <div className="history-row" key={item.id}><strong>{item.event}</strong><span>{item.playerName ?? "Unknown player"}</span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</section><section><h4>Deaths</h4>{(activity.data?.deaths ?? []).map((item) => <div className="history-row" key={item.id}><strong>{item.victim}</strong><span>{item.killer ? `${item.cause ?? "Unknown"} — ${item.killer}` : item.cause ?? "Unknown"}</span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</section></div></Tabs.Content>
  </Tabs.Root><div className="dialog-actions"><button className="button ghost" onClick={onClose}>Close</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
