"use client";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type ReactNode } from "react";
import type { WorldView } from "@/contracts/world";
import { WorldAdminPanel } from "./world-edit-dialog";
import { WorldSchedulesPanel } from "./world-schedules-dialog";
import { WorldBackupsPanel } from "./world-backups-panel";
import { AppShell } from "./app-shell";
import { StructuredSettings } from "./structured-settings";
import { Toast } from "./toast";
import { humanizeIdentifier, jobStartingMessage } from "@/lib/job-presentation";
import { BuildStatus } from "./build-status";

type SafeWorld = Omit<WorldView, "adminPassword" | "serverPassword" | "env">;
type Tab = "overview" | "players" | "deaths" | "console" | "settings" | "backups" | "schedule" | "admin";
type Live = { reachable: boolean; info?: Record<string, unknown>; players?: { players?: Array<Record<string, unknown>> }; metrics?: Record<string, unknown>; error?: string };
type Activity = { events: Array<{ id: number; kind: string; message: string; createdAt: number }>; sessions: Array<{ id: number; playerName: string | null; event: string; createdAt: number }>; deaths: Array<{ id: number; victim: string; cause: string | null; killer: string | null; killerKind: string | null; createdAt: number }> };
type Logs = { files: string[]; selected: string | null; sizeBytes?: number; content: string };
type Configuration = { path: string; exists: boolean; content: string; running: boolean };
type ConfigVersion = { id: string; note: string | null; createdAt: number; sizeBytes: number };

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }
const tabs: Array<{ id: Tab; label: string }> = [{ id: "overview", label: "Overview" }, { id: "players", label: "Players" }, { id: "deaths", label: "Deaths" }, { id: "console", label: "Console" }, { id: "settings", label: "Server config" }, { id: "backups", label: "Backups" }, { id: "schedule", label: "Schedule" }, { id: "admin", label: "World properties" }];
const stamp = (value: number) => new Date(value).toLocaleString();

export function WorldWorkspace({ worldId }: { worldId: string }) {
  const client = useQueryClient(); const [tab, setTab] = useState<Tab>("overview"); const [settingsMode, setSettingsMode] = useState<"structured" | "raw">("structured"); const [notice, setNotice] = useState<string | null>(null); const [draft, setDraft] = useState<string | null>(null); const [logsPaused, setLogsPaused] = useState(false); const [selectedLog, setSelectedLog] = useState<string>();
  const worldQuery = useQuery({ queryKey: ["world", worldId], queryFn: async () => (await json<{ world: SafeWorld }>(`/api/worlds/${worldId}`)).world, refetchInterval: 4_000 });
  const world = worldQuery.data;
  const liveQuery = useQuery({ queryKey: ["world-status", worldId], queryFn: async () => (await json<{ status: Live }>(`/api/worlds/${worldId}/status`)).status, refetchInterval: world?.status === "running" ? 5_000 : false });
  const activityQuery = useQuery({ queryKey: ["world-activity", worldId], queryFn: async () => (await json<{ activity: Activity }>(`/api/worlds/${worldId}/activity`)).activity, refetchInterval: 10_000 });
  const logsQuery = useQuery({ queryKey: ["world-logs", worldId, selectedLog], queryFn: async () => (await json<{ logs: Logs }>(`/api/worlds/${worldId}/logs${selectedLog ? `?file=${encodeURIComponent(selectedLog)}` : ""}`)).logs, refetchInterval: tab === "console" && world?.status === "running" && !logsPaused ? 2_000 : false });
  const configurationQuery = useQuery({ queryKey: ["configuration", worldId], queryFn: async () => (await json<{ configuration: Configuration }>(`/api/worlds/${worldId}/configuration`)).configuration });
  const versionsQuery = useQuery({ queryKey: ["configuration-versions", worldId], queryFn: async () => (await json<{ versions: ConfigVersion[] }>(`/api/worlds/${worldId}/configuration/versions`)).versions });
  const action = useMutation({ mutationFn: (payload: Record<string, unknown>) => json<{ jobId: string }>(`/api/worlds/${worldId}/actions`, { method: "POST", body: JSON.stringify(payload) }), onSuccess: (_, payload) => { setNotice(`${jobStartingMessage(String(payload.action))}…`); void client.invalidateQueries({ queryKey: ["world", worldId] }); void client.invalidateQueries({ queryKey: ["jobs"] }); }, onError: (error) => setNotice(error.message) });
  const saveConfig = useMutation({ mutationFn: () => json(`/api/worlds/${worldId}/configuration`, { method: "PUT", body: JSON.stringify({ content: draft ?? configurationQuery.data?.content ?? "" }) }), onSuccess: () => { setNotice("Configuration saved; restart to apply changes"); void configurationQuery.refetch(); void versionsQuery.refetch(); void client.invalidateQueries({ queryKey: ["configuration-options", worldId] }); }, onError: (error) => setNotice(error.message) });
  const restoreConfig = useMutation({ mutationFn: (versionId: string) => json<{ result: { content: string } }>(`/api/worlds/${worldId}/configuration/versions/${versionId}/restore`, { method: "POST" }), onSuccess: ({ result }) => { setDraft(result.content); setNotice("Configuration version restored; restart to apply changes"); void versionsQuery.refetch(); void client.invalidateQueries({ queryKey: ["configuration", worldId] }); void client.invalidateQueries({ queryKey: ["configuration-options", worldId] }); }, onError: (error) => setNotice(error.message) });
  if (worldQuery.isLoading) return <AppShell active="worlds" className="world-workspace"><div className="empty">Loading world…</div></AppShell>;
  if (!world) return <AppShell active="worlds" className="world-workspace"><div className="empty error">World not found.</div></AppShell>;
  const live = liveQuery.data; const metrics = live?.metrics ?? {}; const players = live?.players?.players ?? [];
  const run = (name: string) => action.mutate({ action: name });
  return <AppShell active="worlds" className="world-workspace">
    <Link className="back-link" href="/">← All worlds</Link>
    <Toast message={notice} onDismiss={() => setNotice(null)} />
    <section className="world-banner"><div className="world-banner-head"><div className="world-icon large">{world.displayName.slice(0, 1).toUpperCase()}</div><div className="world-title"><div><h1>{world.displayName}</h1><Status value={world.status} /></div><p>{String(live?.info?.servername ?? world.installDir)}</p></div><div className="world-primary-actions">{world.status === "running" ? <><button className="button ghost" onClick={() => run("restart")}>Restart</button><button className="button danger" onClick={() => run("stop")}>Stop</button></> : world.status === "starting" || world.status === "stopping" ? <button className="button" disabled>{world.status === "starting" ? "Starting…" : "Stopping…"}</button> : <button className="button primary" onClick={() => run("start")}>Start</button>}<button className="button ghost" disabled={world.status === "starting" || world.status === "stopping"} onClick={() => run("check-update")}>Check build</button><button className="button ghost" disabled={world.status === "running" || world.status === "starting" || world.status === "stopping"} onClick={() => run(world.buildId ? "update" : "install")}>{world.latestBuildId && world.buildId !== world.latestBuildId ? "Update available" : "Update"}</button></div></div>
      <div className="quick-stats"><Quick label="Players" value={live?.reachable ? `${players.length}/${String(metrics.maxplayernum ?? "—")}` : "—"} /><Quick label="Uptime" value={formatUptime(Number(metrics.uptime ?? 0), live?.reachable)} /><Quick label="In-game day" value={live?.reachable ? String(metrics.days ?? "—") : "—"} /><Quick label="Server FPS" value={live?.reachable ? String(metrics.serverfps ?? "—") : "—"} /><Quick label="Installed build" value={<BuildStatus installed={world.buildId} latest={world.latestBuildId} />} /><Quick label="Game port" value={String(world.gamePort)} /></div>
      <div className="connection-row"><span>Connect from this PC</span><code>127.0.0.1:{world.gamePort}</code><button onClick={() => void navigator.clipboard.writeText(`127.0.0.1:${world.gamePort}`)}>Copy</button></div>
    </section>
    <div className="world-tabs">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>
    <section className="world-tab-panel">
      {tab === "overview" && <Overview activity={activityQuery.data} live={live} />}
      {tab === "players" && <Players worldId={worldId} players={players} reachable={Boolean(live?.reachable)} onRefresh={() => void liveQuery.refetch()} onNotice={setNotice} />}
      {tab === "deaths" && <Deaths records={activityQuery.data?.deaths ?? []} />}
      {tab === "console" && <Console world={world} logs={logsQuery.data} paused={logsPaused} onPause={() => setLogsPaused((value) => !value)} onSelect={setSelectedLog} onRefresh={() => void logsQuery.refetch()} onNotice={setNotice} />}
      {tab === "settings" && <div><div className="settings-mode"><button className={settingsMode === "structured" ? "active" : ""} onClick={() => setSettingsMode("structured")}>Guided settings</button><button className={settingsMode === "raw" ? "active" : ""} onClick={() => setSettingsMode("raw")}>Raw INI & history</button></div>{settingsMode === "structured" ? <StructuredSettings worldId={worldId} onNotice={setNotice} /> : <><div className="panel-heading"><div><h2>PalWorldSettings.ini</h2><p>{configurationQuery.data?.path}</p></div><button className="button primary" disabled={saveConfig.isPending} onClick={() => saveConfig.mutate()}>Save raw settings</button></div><textarea className="settings-editor" value={draft ?? configurationQuery.data?.content ?? ""} onChange={(event) => setDraft(event.target.value)} spellCheck={false} /><h2 className="settings-history-title">Version history</h2><div className="record-list">{(versionsQuery.data ?? []).map((version) => <div key={version.id}><span><strong>{version.note ?? "configuration version"}</strong><small>{stamp(version.createdAt)} · {version.sizeBytes} bytes</small></span><button disabled={restoreConfig.isPending || world.status === "running"} onClick={() => restoreConfig.mutate(version.id)}>Restore</button></div>)}{!(versionsQuery.data ?? []).length && <p className="muted">No saved versions yet.</p>}</div></>}</div>}
      {tab === "backups" && <WorldBackupsPanel worldId={worldId} running={world.status === "running"} onBackup={() => action.mutate({ action: "backup", reason: "manual" })} onRestore={(backupId) => { if (window.confirm("Restore this verified backup? A safety backup will be created first.")) action.mutate({ action: "restore", backupId }); }} onNotice={setNotice} />}
      {tab === "schedule" && <WorldSchedulesPanel world={world} onNotice={setNotice} />}
      {tab === "admin" && <WorldAdminPanel world={world} onSaved={() => void worldQuery.refetch()} onNotice={setNotice} />}
    </section>
  </AppShell>;
}
function Status({ value }: { value: SafeWorld["status"] }) { return <span className={`status status-${value}`}><i />{value}</span>; }
function Quick({ label, value }: { label: string; value: ReactNode }) { return <article><strong>{value}</strong><span>{label}</span></article>; }
function formatUptime(seconds: number, reachable?: boolean) { if (!reachable) return "—"; const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return `${hours}h ${minutes}m`; }
function Overview({ activity, live }: { activity?: Activity; live?: Live }) { return <div className="overview-columns"><section><h2>Recent activity</h2>{(activity?.events ?? []).length ? activity!.events.map((item) => <div className="history-row" key={item.id}><strong>{humanizeIdentifier(item.kind)}</strong><span>{item.message}</span><time>{stamp(item.createdAt)}</time></div>) : <p className="muted">No recorded events.</p>}</section><section><h2>Join/leave history</h2>{(activity?.sessions ?? []).length ? activity!.sessions.map((item) => <div className="history-row" key={item.id}><strong>{humanizeIdentifier(item.event)}</strong><span>{item.playerName ?? "Unknown player"}</span><time>{stamp(item.createdAt)}</time></div>) : <p className="muted">No player sessions recorded.</p>}<h2 className="health-heading">Server health</h2><p className={live?.reachable ? "green" : "muted"}>{live?.reachable ? "REST API reachable" : live?.error ?? "Server offline"}</p></section></div>; }
function Players({ worldId, players, reachable, onRefresh, onNotice }: { worldId: string; players: Array<Record<string, unknown>>; reachable: boolean; onRefresh(): void; onNotice(message: string): void }) {
  const [manualUserId, setManualUserId] = useState("");
  const admin = useMutation({
    mutationFn: (payload: Record<string, unknown>) => json(`/api/worlds/${worldId}/admin`, { method: "POST", body: JSON.stringify(payload) }),
    onSuccess: (_, payload) => { const action = String(payload.action); const name = String(payload.playerName ?? payload.userId ?? "player"); onNotice(action === "kick" ? `${name} was kicked.` : action === "ban" ? `${name} was banned.` : `${name} was unbanned.`); onRefresh(); },
    onError: (error) => onNotice(error.message),
  });
  function act(action: "kick" | "ban" | "unban", userId: string, name: string) {
    if (action !== "unban" && !window.confirm(`${action === "kick" ? "Kick" : "Ban"} ${name}?`)) return;
    admin.mutate({ action, userId, playerName: name });
  }
  if (!reachable) return <div className="tab-empty"><h2>Players</h2><p>Start the server with its REST API enabled to view and moderate players.</p></div>;
  return <div className="players-panel"><div className="panel-heading"><div><h2>Online players</h2><p>Kick and ban use the player&apos;s REST user ID, not their display name.</p></div><button className="button ghost" onClick={onRefresh}>Refresh</button></div>
    {players.length ? <div className="player-table"><div className="player-table-head"><span>Player</span><span>Level</span><span>Ping</span><span>Location</span><span>Actions</span></div>{players.map((player, index) => { const userId = String(player.userId ?? player.userid ?? player.playerId ?? player.name ?? index); const name = String(player.name ?? player.playername ?? "Unknown player"); return <div className="player-row" key={userId}><span><strong>{name}</strong><small>{String(player.accountName ?? player.accountname ?? userId)}</small></span><span>{String(player.level ?? "—")}</span><span>{player.ping == null ? "—" : `${Math.round(Number(player.ping))} ms`}</span><span>{player.location_x == null ? "—" : `${Math.round(Number(player.location_x))}, ${Math.round(Number(player.location_y))}`}</span><span className="player-actions"><button disabled={admin.isPending} onClick={() => act("kick", userId, name)}>Kick</button><button className="danger" disabled={admin.isPending} onClick={() => act("ban", userId, name)}>Ban</button></span></div>; })}</div> : <div className="tab-empty compact"><p>No players are online.</p></div>}
    <section className="manual-moderation"><div><h2>Moderate by user ID</h2><p>Use this to unban an offline player or act on a known user ID.</p></div><input value={manualUserId} onChange={(event) => setManualUserId(event.target.value)} placeholder="Player user ID" /><button disabled={!manualUserId.trim() || admin.isPending} onClick={() => act("kick", manualUserId.trim(), manualUserId.trim())}>Kick</button><button className="danger" disabled={!manualUserId.trim() || admin.isPending} onClick={() => act("ban", manualUserId.trim(), manualUserId.trim())}>Ban</button><button disabled={!manualUserId.trim() || admin.isPending} onClick={() => act("unban", manualUserId.trim(), manualUserId.trim())}>Unban</button></section>
  </div>;
}

function Deaths({ records }: { records: Activity["deaths"] }) {
  return <div><div className="panel-heading"><div><h2>Death history</h2><p>Preserved records from the legacy manager, newest first.</p></div></div>{records.length ? <div className="record-list">{records.map((item) => <div key={item.id}><span><strong>{item.victim}</strong><small>{item.killer ? `${item.cause ?? "Unknown cause"} · ${item.killerKind === "player" ? "Killed by player" : "Killed by"} ${item.killer}` : item.cause ?? "Unknown cause"}</small><small>{stamp(item.createdAt)}</small></span></div>)}</div> : <div className="tab-empty"><h2>No recorded deaths</h2><p>Live death capture requires the deferred PSM Death Relay extension. Existing imported history will appear here.</p></div>}</div>;
}

function Console({ world, logs, paused, onPause, onSelect, onRefresh, onNotice }: { world: SafeWorld; logs?: Logs; paused: boolean; onPause(): void; onSelect(file: string): void; onRefresh(): void; onNotice(message: string): void }) {
  const [search, setSearch] = useState(""); const [announcement, setAnnouncement] = useState(""); const [rconCommand, setRconCommand] = useState(""); const [rconOutput, setRconOutput] = useState("");
  const admin = useMutation({ mutationFn: (payload: Record<string, unknown>) => json(`/api/worlds/${world.id}/admin`, { method: "POST", body: JSON.stringify(payload) }), onSuccess: (_, payload) => { if (payload.action === "announce") { setAnnouncement(""); onNotice("Announcement sent to the server."); } else onNotice("World save requested successfully."); }, onError: (error) => onNotice(error.message) });
  const rcon = useMutation({ mutationFn: (command: string) => json<{ output: string }>(`/api/worlds/${world.id}/rcon`, { method: "POST", body: JSON.stringify({ command }) }), onSuccess: ({ output }, command) => { setRconOutput(`> ${command}\n${output || "Command completed without a text response."}`); setRconCommand(""); }, onError: (error) => { setRconOutput(`Error: ${error.message}`); onNotice(error.message); } });
  const needle = search.trim().toLocaleLowerCase(); const lines = (logs?.content ?? "").split("\n"); const matches = needle ? lines.filter((line) => line.toLocaleLowerCase().includes(needle)) : lines; const shown = matches.join("\n");
  return <div className="console-panel"><div className="panel-heading"><div><h2>Live server log</h2><p>{logs?.selected ?? "No server log yet"}{logs?.sizeBytes && logs.sizeBytes > 250_000 ? " · showing the newest 250 KB" : ""}</p></div><div className="console-heading-actions"><button className={`button ${paused ? "primary" : "ghost"}`} onClick={onPause}>{paused ? "Resume live updates" : "Pause live updates"}</button><button className="button ghost" onClick={onRefresh}>Refresh now</button></div></div>
    <div className="console-tools"><label>Log file<select value={logs?.selected ?? ""} onChange={(event) => onSelect(event.target.value)} disabled={!logs?.files.length}>{(logs?.files ?? []).map((file) => <option key={file}>{file}</option>)}</select></label><label>Search this log<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Error, player name, endpoint…" /></label>{logs?.selected && <a className="button ghost" href={`/api/worlds/${world.id}/logs/download?file=${encodeURIComponent(logs.selected)}`}>Download full log</a>}<span>{needle ? `${matches.length} matching line${matches.length === 1 ? "" : "s"}` : paused ? "Updates paused" : "Updating every 2 seconds"}</span></div>
    <pre className="console-output">{shown || (needle ? "No lines match this search." : "Waiting for server output.")}</pre>
    <section className="live-admin"><div><h2>Live administration</h2><p>Uses Palworld&apos;s local REST API. Actions are recorded in world history.</p></div><div className="announce-row"><input value={announcement} maxLength={2_000} onChange={(event) => setAnnouncement(event.target.value)} placeholder="Announcement to all online players" disabled={world.status !== "running" || !world.restApiEnabled} /><button className="button primary" disabled={!announcement.trim() || admin.isPending || world.status !== "running" || !world.restApiEnabled} onClick={() => admin.mutate({ action: "announce", message: announcement })}>Send announcement</button><button className="button ghost" disabled={admin.isPending || world.status !== "running" || !world.restApiEnabled} onClick={() => admin.mutate({ action: "save" })}>Save world now</button></div>{!world.restApiEnabled && <p className="form-warning">Enable REST API in World Properties and restart the server to use these controls.</p>}</section>
    {world.rconEnabled && <section className="legacy-rcon"><div><h2>Legacy RCON console</h2><p>Deprecated by Pocketpair. Prefer the REST controls above; this console is available only because RCON is explicitly enabled for this world.</p></div><div className="announce-row"><input value={rconCommand} onChange={(event) => setRconCommand(event.target.value)} placeholder="RCON command" disabled={world.status !== "running"} onKeyDown={(event) => { if (event.key === "Enter" && rconCommand.trim() && !rcon.isPending) rcon.mutate(rconCommand); }} /><button className="button ghost" disabled={!rconCommand.trim() || rcon.isPending || world.status !== "running"} onClick={() => rcon.mutate(rconCommand)}>{rcon.isPending ? "Running…" : "Run command"}</button></div>{rconOutput && <pre className="rcon-output">{rconOutput}</pre>}</section>}
  </div>;
}
