"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import type { WorldView } from "@/contracts/world";

type SafeWorld = Omit<WorldView, "adminPassword" | "serverPassword" | "env">;
type Action = "backup" | "restart" | "stop" | "update" | "system_message" | "onscreen_notice" | "custom_http" | "idle_stop";
type Mode = "interval" | "minutes" | "daily" | "on_join";
type Schedule = { id: string; action: Action; mode: Mode; intervalHours: number | null; intervalMinutes: number | null; timeOfDay: string | null; message: string | null; joinMatch: string | null; joinDelaySeconds: number | null; enabled: boolean; skipNext: boolean; lastRunAt: number | null; nextRunAt: number | null };
type WarningSettings = { warningEnabled: boolean; warningLeadMinutes: number; warningIntervalMinutes: number; warningMessage: string };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }
const when = (value: number | null) => value ? new Date(value).toLocaleString() : "event driven";
const actionLabels: Record<Action, string> = { backup: "Verified backup", restart: "Graceful restart", stop: "Graceful stop", update: "Update server", system_message: "System message", onscreen_notice: "On-screen notice", custom_http: "Custom HTTP request", idle_stop: "Stop when empty" };

export function WorldSchedulesPanel({ world, onNotice }: { world: SafeWorld; onNotice(message: string): void }) {
  const client = useQueryClient(); const [mode, setMode] = useState<Mode>("interval"); const [action, setAction] = useState<Action>("backup");
  const key = ["schedules", world.id];
  const query = useQuery({ queryKey: key, queryFn: async () => (await request<{ schedules: Schedule[] }>(`/api/worlds/${world.id}/schedules`)).schedules });
  const warningQuery = useQuery({ queryKey: ["maintenance-settings", world.id], queryFn: async () => (await request<{ settings: WarningSettings }>(`/api/worlds/${world.id}/schedules/settings`)).settings });
  const refresh = () => void client.invalidateQueries({ queryKey: key });
  const create = useMutation({ mutationFn: (payload: object) => request(`/api/worlds/${world.id}/schedules`, { method: "POST", body: JSON.stringify(payload) }), onSuccess: () => { onNotice("Schedule created"); refresh(); }, onError: (error) => onNotice(error.message) });
  const patch = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: object }) => request(`/api/schedules/${id}`, { method: "PATCH", body: JSON.stringify(payload) }), onSuccess: refresh, onError: (error) => onNotice(error.message) });
  const remove = useMutation({ mutationFn: (id: string) => request(`/api/schedules/${id}`, { method: "DELETE" }), onSuccess: () => { onNotice("Schedule deleted"); refresh(); }, onError: (error) => onNotice(error.message) });
  function changeAction(value: Action) { setAction(value); if (value === "idle_stop" && (mode === "daily" || mode === "on_join")) setMode("interval"); if (value !== "system_message" && value !== "onscreen_notice" && mode === "on_join") setMode("interval"); }
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    create.mutate({ action, mode, ...(mode === "interval" ? { intervalHours: Number(data.get("intervalHours")) } : {}), ...(mode === "minutes" ? { intervalMinutes: Number(data.get("intervalMinutes")) } : {}), ...(mode === "daily" ? { timeOfDay: data.get("timeOfDay") } : {}), ...((action === "system_message" || action === "onscreen_notice") ? { message: data.get("message"), ...(mode === "on_join" ? { joinMatch: data.get("joinMatch"), joinDelaySeconds: Number(data.get("joinDelaySeconds")) } : {}) } : {}), ...(action === "custom_http" ? { httpMethod: data.get("httpMethod"), httpUrl: data.get("httpUrl"), httpHeaders: data.get("httpHeaders"), httpBody: data.get("httpBody") } : {}), enabled: true });
  }
  const modes: Mode[] = action === "idle_stop" ? ["interval", "minutes"] : action === "system_message" || action === "onscreen_notice" ? ["interval", "minutes", "daily", "on_join"] : ["interval", "minutes", "daily"];
  return <div className="schedule-panel"><WarningConfiguration worldId={world.id} data={warningQuery.data} loading={warningQuery.isLoading} onNotice={onNotice} onSaved={() => void warningQuery.refetch()} />
    <div className="panel-heading"><div><h2>Automated operations</h2><p>Schedules run in the persistent manager runtime. Daily times use this computer&apos;s local timezone.</p></div></div>
    <form className="schedule-form expanded" onSubmit={submit}><label>Action<select name="action" value={action} onChange={(event) => changeAction(event.target.value as Action)}>{Object.entries(actionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>When<select name="mode" value={mode} onChange={(event) => setMode(event.target.value as Mode)}>{modes.map((value) => <option key={value} value={value}>{value === "interval" ? action === "idle_stop" ? "After N hours empty" : "Every N hours" : value === "minutes" ? action === "idle_stop" ? "After N minutes empty" : "Every N minutes" : value === "daily" ? "Daily at local time" : "When a player joins"}</option>)}</select></label>
      {mode === "interval" && <label>Hours<input name="intervalHours" type="number" min="1" max="720" defaultValue="6" /></label>}{mode === "minutes" && <label>Minutes<input name="intervalMinutes" type="number" min="1" max="43200" defaultValue="60" /></label>}{mode === "daily" && <label>Local time<input name="timeOfDay" type="time" defaultValue="04:00" /></label>}
      {(action === "system_message" || action === "onscreen_notice") && <label className="schedule-wide">Message<input name="message" required maxLength={2000} placeholder={mode === "on_join" ? "Welcome {player}!" : "Scheduled maintenance begins soon."} /><small>{action === "onscreen_notice" ? "Uses REST chat fallback until the broadcast mod is available." : "Sent through Palworld REST as a System announcement."}</small></label>}
      {mode === "on_join" && <><label>Only this player<input name="joinMatch" maxLength={128} placeholder="Blank means anyone" /></label><label>Delay after join (seconds)<input name="joinDelaySeconds" type="number" min="0" max="3600" defaultValue="5" /></label></>}
      {action === "custom_http" && <><label>Method<select name="httpMethod" defaultValue="POST"><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select></label><label className="schedule-wide">URL<input name="httpUrl" type="url" required placeholder="https://example.internal/hook" /></label><label className="schedule-wide">Headers<textarea name="httpHeaders" placeholder={'Authorization: Bearer …\nContent-Type: application/json'} /></label><label className="schedule-wide">Body<textarea name="httpBody" placeholder='{"world":"maintenance"}' /></label></>}
      <button className="button primary" disabled={create.isPending}>Add schedule</button></form>
    <div className="schedule-list">{query.isLoading ? <p className="muted">Loading schedules…</p> : (query.data ?? []).length === 0 ? <p className="muted">No schedules for this world.</p> : (query.data ?? []).map((item) => <article key={item.id}><div><strong>{actionLabels[item.action] ?? item.action.replaceAll("_", " ")}</strong><span>{describe(item)}</span><small>Next: {when(item.nextRunAt)}{item.lastRunAt ? ` · Last: ${when(item.lastRunAt)}` : " · Never run"}{item.skipNext ? " · Next occurrence will be skipped" : ""}</small></div><div className="schedule-actions"><button onClick={() => patch.mutate({ id: item.id, payload: { enabled: !item.enabled } })}>{item.enabled ? "Disable" : "Enable"}</button><button disabled={!item.enabled || item.skipNext} onClick={() => patch.mutate({ id: item.id, payload: { skipNext: true } })}>{item.skipNext ? "Will skip" : "Skip next"}</button><button className="danger" onClick={() => { if (window.confirm(`Delete the ${actionLabels[item.action]} schedule?`)) remove.mutate(item.id); }}>Delete</button></div></article>)}</div>
  </div>;
}

function describe(item: Schedule): string {
  if (item.mode === "on_join") return `${item.joinMatch ? `when ${item.joinMatch}` : "when anyone"} joins${item.joinDelaySeconds ? ` after ${item.joinDelaySeconds}s` : ""}`;
  if (item.mode === "daily") return `daily at ${item.timeOfDay}`;
  if (item.mode === "minutes") return `${item.action === "idle_stop" ? "empty for" : "every"} ${item.intervalMinutes} minutes`;
  return `${item.action === "idle_stop" ? "empty for" : "every"} ${item.intervalHours ?? Math.ceil((item.intervalMinutes ?? 0) / 60)} hours`;
}

function WarningConfiguration({ worldId, data, loading, onNotice, onSaved }: { worldId: string; data?: WarningSettings; loading: boolean; onNotice(message: string): void; onSaved(): void }) {
  const [enabledDraft, setEnabledDraft] = useState<boolean>(); const [leadDraft, setLeadDraft] = useState<number>(); const [intervalDraft, setIntervalDraft] = useState<number>(); const [messageDraft, setMessageDraft] = useState<string>();
  const enabled = enabledDraft ?? data?.warningEnabled ?? false; const lead = leadDraft ?? data?.warningLeadMinutes ?? 10; const interval = intervalDraft ?? data?.warningIntervalMinutes ?? 2; const message = messageDraft ?? data?.warningMessage ?? "The server will {action} in {minutes} minute(s). Please get to a safe place.";
  const save = useMutation({ mutationFn: () => request(`/api/worlds/${worldId}/schedules/settings`, { method: "PUT", body: JSON.stringify({ warningEnabled: enabled, warningLeadMinutes: lead, warningIntervalMinutes: interval, warningMessage: message }) }), onSuccess: () => { setEnabledDraft(undefined); setLeadDraft(undefined); setIntervalDraft(undefined); setMessageDraft(undefined); onNotice("Player warning settings saved"); onSaved(); }, onError: (error) => onNotice(error.message) });
  return <section className={`warning-settings ${enabled ? "enabled" : ""}`}><div><h2>Warn players before maintenance</h2><p>For scheduled restart, stop, and update jobs, announce a countdown before Palworld&apos;s native final shutdown timer.</p></div><button className={`toggle ${enabled ? "on" : ""}`} onClick={() => setEnabledDraft(!enabled)}><i />{enabled ? "On" : "Off"}</button>{enabled && <div className="warning-fields"><label>Start warning (minutes)<input type="number" min="1" max="120" value={lead} onChange={(event) => setLeadDraft(Number(event.target.value))} /></label><label>Repeat every (minutes)<input type="number" min="0" max="120" value={interval} onChange={(event) => setIntervalDraft(Number(event.target.value))} /></label><label className="schedule-wide">Message<input value={message} onChange={(event) => setMessageDraft(event.target.value)} /><small>Available placeholders: {'{action}'}, {'{minutes}'}, {'{seconds}'}.</small></label></div>}<button className="button ghost warning-save" disabled={loading || save.isPending} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save warning settings"}</button></section>;
}
