export const PALWORLD_SETTING_GUIDANCE = {
  "Difficulty": "Named difficulty preset. None leaves balance to the individual settings below; do not assume a named preset replaces explicit multipliers.",
  "DeathPenalty": "Controls death losses. None: nothing; Item: inventory except equipment; ItemAndEquipment: inventory and equipment; All: those items plus party Pals.",
  "bHardcore": "Enables hardcore character death and prevents normal respawning. Use with the other hardcore options.",
  "bPalLost": "When on, permanently removes party Pals on player death. This can delete substantial breeding progress.",
  "bCharacterRecreateInHardcore": "When on, a player may create a replacement character after hardcore death; off can make one death final.",
  "RandomizerType": "None keeps normal Pal spawns; Region randomizes within regions; All randomizes across the world.",
  "RandomizerSeed": "Seed for reproducible randomized Pal spawns. Changing it changes the distribution; it is ignored when randomization is off.",
  "bIsRandomizerPalLevelRandom": "On fully randomizes wild Pal levels; off keeps randomized levels within each area's intended range.",
  "DayTimeSpeedRate": "Daytime clock-speed multiplier. Higher makes daytime pass faster and become shorter; lower makes it pass slower and last longer.",
  "NightTimeSpeedRate": "Nighttime clock-speed multiplier. Higher makes night pass faster and become shorter; lower makes it pass slower and last longer.",
  "ExpRate": "Experience gain multiplier. Higher speeds progression; lower slows it.",
  "WorkSpeedRate": "General base-Pal work-speed multiplier. Higher completes crafting and base work faster; lower makes work slower.",
  "MonsterFarmActionSpeedRate": "Ranch/grazing production-speed multiplier. Higher produces ranch items faster; lower produces them more slowly.",
  "AutoSaveSpan": "Time between automatic world saves. Lower saves more often but increases disk work; higher reduces disk work but increases possible crash-related progress loss.",
  "PalCaptureRate": "Capture-chance multiplier. Higher makes captures easier; lower makes them harder.",
  "PalSpawnNumRate": "Wild Pal spawn-density multiplier. Higher creates more Pals and raises CPU/memory load; lower creates fewer.",
  "PalDamageRateAttack": "Pal damage-dealt multiplier. Higher strengthens Pal attacks; lower weakens them.",
  "PalDamageRateDefense": "Pal damage-received multiplier despite the legacy “defense” name. Higher makes Pals take more damage; lower makes them tougher.",
  "PalStomachDecreaceRate": "Pal hunger-depletion multiplier. Higher makes Pals hungry faster; lower slows hunger. The misspelling is part of the real key.",
  "PalStaminaDecreaceRate": "Pal stamina-depletion multiplier. Higher drains stamina faster; lower makes it last longer.",
  "PalAutoHPRegeneRate": "Natural Pal HP-regeneration multiplier. Higher restores HP faster; lower restores it more slowly.",
  "PalAutoHpRegeneRateInSleep": "Pal HP regeneration while sleeping/in the Palbox. Higher restores HP faster; lower restores it more slowly.",
  "PalEggDefaultHatchingTime": "Base incubation time for a Huge Egg; other sizes scale from it. Higher lengthens incubation; lower shortens it; 0 is commonly used for instant incubation.",
  "EnablePredatorBossPal": "Enables roaming Predator boss Pals. Off removes this encounter type.",
  "PlayerDamageRateAttack": "Player damage-dealt multiplier. Higher strengthens player attacks; lower weakens them.",
  "PlayerDamageRateDefense": "Player damage-received multiplier despite the legacy “defense” name. Higher makes players take more damage; lower makes them tougher.",
  "PlayerStomachDecreaceRate": "Player hunger-depletion multiplier. Higher makes players hungry faster; lower slows hunger.",
  "PlayerStaminaDecreaceRate": "Player stamina-depletion multiplier. Higher drains stamina faster; lower makes it last longer.",
  "PlayerAutoHPRegeneRate": "Natural player HP-regeneration multiplier. Higher restores HP faster; lower restores it more slowly.",
  "PlayerAutoHpRegeneRateInSleep": "Player HP regeneration while sleeping. Higher restores HP faster; lower restores it more slowly.",
  "ItemWeightRate": "Item-weight multiplier. Higher makes items heavier and reduces effective capacity; lower makes them lighter.",
  "BlockRespawnTime": "Base delay before respawn. Higher forces a longer wait after death; lower allows faster respawning.",
  "RespawnPenaltyDurationThreshold": "Survival-time threshold used by the repeated-death penalty. A positive value defines how long a player must survive before escalation resets; 0 disables the time window.",
  "RespawnPenaltyTimeScale": "Multiplier applied to respawn delay when the repeated-death penalty triggers. Higher escalates the wait more strongly; lower softens it.",
  "bAllowEnhanceStat_Health": "Allows new enhancement-point allocations to Health. Off blocks new allocations; it does not document removal of points already spent.",
  "bAllowEnhanceStat_Attack": "Allows new enhancement-point allocations to Attack. Pocketpair recommends disabling Attack and Health in some PvP rule sets.",
  "bAllowEnhanceStat_Stamina": "Allows new enhancement-point allocations to Stamina; off blocks them.",
  "bAllowEnhanceStat_Weight": "Allows new enhancement-point allocations to Carry Weight; off blocks them.",
  "bAllowEnhanceStat_WorkSpeed": "Allows new enhancement-point allocations to Work Speed; off blocks them.",
  "CollectionDropRate": "Gatherable-resource yield multiplier. Higher gives more ore, wood, and similar resources per gather; lower gives fewer.",
  "CollectionObjectHpRate": "Gatherable-object health multiplier. Higher requires more damage to break a node; lower makes it easier.",
  "CollectionObjectRespawnSpeedRate": "Gatherable respawn-interval multiplier despite “speed” in the name. Higher means slower respawns; lower means faster respawns. 0.5 is roughly twice as fast.",
  "EnemyDropItemRate": "Enemy loot-quantity multiplier. Higher produces more enemy loot; lower produces less.",
  "DropItemMaxNum": "Maximum dropped items retained in the world. Higher permits more clutter and memory/physics work; lower removes excess drops sooner.",
  "PhysicsActiveDropItemMaxNum": "Maximum dropped items allowed to use full physics behavior. A positive cap can reduce physics load; a higher cap permits more simultaneously simulated drops.",
  "DropItemMaxNum_UNKO": "Separate maximum for Pal waste drops. Higher permits more waste objects; lower limits buildup.",
  "DropItemAliveMaxHours": "Dropped-item lifetime. Higher keeps drops longer and can increase world load; lower cleans them up sooner.",
  "SupplyDropSpan": "Meteorite/supply-drop interval. Higher makes events less frequent; lower makes them more frequent. The official unit is minutes, not seconds.",
  "bEnableInvaderEnemy": "Enables base invasion/raid events. Off disables raids; raids add AI activity and server load.",
  "bActiveUNKO": "Enables Pal waste-object production. On can add dropped-object clutter; off prevents it.",
  "EquipmentDurabilityDamageRate": "Equipment durability-loss multiplier. Higher wears equipment faster; lower makes it last longer.",
  "ItemCorruptionMultiplier": "Perishable-item spoilage-speed multiplier. Higher spoils items faster; lower preserves them longer.",
  "FishingDifficultyRate": "Fishing-difficulty multiplier. Lower makes fishing easier; higher makes it harder.",
  "bAllowEnemyCampSpawnNearBaseCamp": "On allows enemy camps to spawn close to player bases; off keeps them farther away.",
  "DenyTechnologyList": "Technology IDs players may not unlock. Add IDs to prohibit them; remove IDs to permit them. Exact tuple syntax and valid IDs are required.",
  "BuildObjectHpRate": "Structure-health multiplier. Higher makes structures tougher; lower makes them easier to destroy.",
  "BuildObjectDamageRate": "Structure damage-received multiplier. Higher makes structures take more damage; lower makes them tougher.",
  "BuildObjectDeteriorationDamageRate": "Structure-decay multiplier. Higher accelerates decay; lower slows it; 0 disables deterioration.",
  "BaseCampMaxNum": "Total bases across the server. Higher allows more bases but raises processing/save load; lower constrains total growth.",
  "BaseCampWorkerMaxNum": "Maximum working Pals at one base. Higher allows more workers and raises processing load; lower limits them. Behavior above 15 should be verified in game.",
  "BaseCampMaxNumInGuild": "Maximum bases per guild. Higher permits more bases and raises load, but progression may still gate slot unlocks; lower caps expansion.",
  "MaxBuildingLimitNum": "Server-wide structure-count cap in current releases. A positive value limits total structures; higher allows more building but raises load. Older documentation described this as per-player.",
  "MaxBuildingLimitNumPerPlayer": "Per-player structure-count cap. A positive value limits each player separately; higher permits more structures per player.",
  "bBuildAreaLimit": "On prevents building near important locations such as spawn and fast-travel points; off uses the broader normal build rules.",
  "bEnableBuildingPlayerUIdDisplay": "On shows the builder's player ID on structures to help moderation; off hides it.",
  "GuildPlayerMaxNum": "Maximum guild membership. Higher permits larger guilds; lower creates smaller groups.",
  "bAutoResetGuildNoOnlinePlayers": "Enables deletion of fully inactive guilds' structures and base Pals after the threshold below. This is destructive.",
  "AutoResetGuildTimeNoOnlinePlayers": "Inactivity before automatic guild reset. Higher gives guilds more time; lower deletes property sooner. Ignored when auto-reset is off.",
  "bEnableDefenseOtherGuildPlayer": "On lets base Pals attack trespassers from other guilds and is part of Pocketpair's required PvP combination.",
  "bCanPickupOtherGuildDeathPenaltyDrop": "On allows looting another guild's death drops; off preserves normal ownership rules.",
  "bInvisibleOtherGuildBaseCampAreaFX": "Controls other guilds' base-boundary effects. The negative key conflicts with Pocketpair's positive description; treat on as “hide” but verify visually.",
  "GuildRejoinCooldownMinutes": "Delay before rejoining a guild after leaving. Higher enforces a longer wait; 0 permits immediate rejoining.",
  "AutoTransferMasterCheckIntervalSeconds": "How often the server checks whether an inactive guild master qualifies for automatic transfer. Lower checks more often; higher delays detection.",
  "AutoTransferMasterThresholdDays": "Guild-master inactivity required before automatic transfer. Lower transfers sooner; higher gives the current master more time to return.",
  "bEnablePlayerToPlayerDamage": "Allows players to damage one another. It is one of three settings required for working PvP.",
  "bEnableFriendlyFire": "On permits damage between members of the same guild; off protects guildmates.",
  "bIsPvP": "Master PvP mode. Working PvP also requires player damage and other-guild defense to be on.",
  "bIsMultiplay": "Legacy multiplayer/co-op-session flag. Pocketpair does not document a useful dedicated-server effect; leave at default unless a tested workflow requires it.",
  "bEnableNonLoginPenalty": "Enables penalties for extended non-login. Pocketpair does not currently explain the exact dedicated-server effect.",
  "bEnableFastTravel": "Enables fast travel. Off disables it entirely; on remains subject to the base-only restriction below.",
  "bEnableFastTravelOnlyBaseCamp": "On restricts fast travel to between bases; off permits normal fast travel. Useful for preventing PvP combat escape.",
  "bIsStartLocationSelectByMap": "On lets new players choose their starting location on the map; off uses normal starting behavior.",
  "bExistPlayerAfterLogout": "On leaves a sleeping player body at the logout location, making logout unsafe as a combat escape; off removes it normally.",
  "bDisplayPvPItemNumOnWorldMap_BaseCamp": "On shows PvP-exclusive item counts at bases on the map; off hides them.",
  "bDisplayPvPItemNumOnWorldMap_Player": "On shows player locations and PvP-exclusive item counts on the map; off hides them.",
  "bAdditionalDropItemWhenPlayerKillingInPvPMode": "Enables the configured extra item drop when a player is killed in PvP.",
  "AdditionalDropItemWhenPlayerKillingInPvPMode": "Item ID for the extra PvP-kill reward. Change it to a valid ID; it is ignored while extra drops are off.",
  "AdditionalDropItemNumWhenPlayerKillingInPvPMode": "Extra PvP reward quantity. Higher drops more per kill; lower drops fewer.",
  "bEnableVoiceChat": "Enables dedicated-server proximity voice chat. Off requires another voice service.",
  "VoiceChatMaxVolumeDistance": "Distance within which voice remains at full volume. Higher keeps it loud farther away; lower starts attenuation sooner. Keep below the silence distance.",
  "VoiceChatZeroVolumeDistance": "Distance at which voice becomes inaudible. Higher lets voices carry farther; lower makes them fade sooner.",
  "bAllowGlobalPalboxExport": "Allows exporting this world's Pals to the account-wide Global Palbox. Off keeps them local.",
  "bAllowGlobalPalboxImport": "Allows importing outside Pals. On lets players bring advanced Pals into the server; off protects local progression.",
  "bEnableAimAssistPad": "Enables controller aim assistance; off disables it.",
  "bEnableAimAssistKeyboard": "Enables mouse/keyboard aim assistance; off leaves it disabled.",
  "bIsUseBackupSaveData": "Enables Palworld's own rolling backups inside save data. On increases disk activity and is separate from manager-created backup archives.",
  "ServerName": "Name in the community-server browser. Changing it does not change the manager's local world label.",
  "ServerDescription": "Description shown with the listing. Empty shows no custom description.",
  "PublicIP": "External IP advertised by a community server. Set only when detection is wrong or a tunnel requires it; it does not bind the listener.",
  "PublicPort": "External port advertised by a community server. It does not change the actual listening port.",
  "Region": "Region label for listing/filtering. It does not change hosting location or latency.",
  "CoopPlayerMaxNum": "Intended co-op party-size cap. It is widely reported not to control dedicated-server capacity; use ServerPlayerMaxNum for that.",
  "ServerPlayerMaxNum": "Maximum concurrent dedicated-server players. Higher admits more players and raises load; lower provides fewer slots. The supported/default ceiling is 32.",
  "CrossplayPlatforms": "Platforms allowed to connect. Remove a platform to reject it; include a supported platform to permit it. Console/Game Pass users rely on the community browser.",
  "bAllowClientMod": "Allows mod-enabled clients to connect. Off rejects them; on does not install or validate their mods.",
  "bUseAuth": "Platform identity authentication. Turning it off weakens access security and is not normally useful.",
  "BanListURL": "Remote global ban-list feed. It is not the server's local player-ban file; do not use an untrusted URL.",
  "bShowPlayerList": "On shows the online player list in the ESC menu; off hides it.",
  "bIsShowJoinLeftMessage": "On announces joins/leaves in game; off suppresses those messages.",
  "ChatPostLimitPerMinute": "Per-player chat rate limit. Higher permits faster posting; lower reduces spam but may impede conversation.",
  "LogFormatType": "Text is human-readable; Json is structured for log-processing tools.",
  "ServerReplicatePawnCullDistance": "Pal synchronization distance. Higher shows distant Pals but costs bandwidth/processing; lower reduces load but causes later pop-in.",
  "ItemContainerForceMarkDirtyInterval": "Forced re-sync interval while a container UI is open. Higher syncs less often and may feel laggy; lower syncs more often and increases work.",
  "PlayerDataPalStorageUpdateCheckTickInterval": "Interval between player Pal-storage update checks. Higher checks less often; lower checks more frequently. Pocketpair does not currently publish a safe range.",
  "MaxGuildsPerFrame": "Maximum guilds processed in one server frame. Higher processes more work per frame; lower spreads work over more frames. Pocketpair does not currently document tuning guidance.",
  "BuildingNameDisplayCacheTTLSeconds": "Lifetime of cached builder-name lookups for structures. Higher retains cached names longer; lower refreshes them more often.",
} as const satisfies Readonly<Record<string, string>>;

export function settingGuidance(key: string): string | undefined {
  return PALWORLD_SETTING_GUIDANCE[key as keyof typeof PALWORLD_SETTING_GUIDANCE];
}
